---
editor_options: 
  markdown: 
    wrap: 72
---

# (PART\*) Section 2 {.unnumbered}

# Overview {.unnumbered}

::: {style="color: #333; font-size: 24px; font-style: italic; text-align: justify;"}
Section 2: Linear Regression and Prediction
:::

::: ilos
**Learning Outcomes:**
:::

**Throughout these two practicals, you will practice using the functions below:**


# Interactive Activities {-}

## Simple Linear Regression {-}

To develop a better understanding the role of the slope and intercept in defining a regression line and to observe how coefficient estimates influence performance measures, explore the below interactive activity. This is an interactive scatterplot that illustrates the relationship between screen time duration and sleep duration. The line in red is the line of best fit, accompanied by the RSE and r-squared values. 
The line in blue is customisable. You can adjust the slope and intercept and derive different line equations. You can compare the different lines you generate with the red line of best fit. Have a look at how the r-squared and RSE values change for different line equations. 

<iframe src="https://ioanamacoveciuc.shinyapps.io/S2_simplereg/" style="width:100%; height:100vh; border:none;"></iframe>


## Multiple Linear Regression {-}

# Practical 1 {-}

# Practical 2 {-}

# Practical 3 {-}

# Practical 4 {-}

# Practical 5 {-}
