# (PART\*) Section 1 {.unnumbered}

# Overview {.unnumbered}

::: {style="color: #333; font-size: 24px; font-style: italic; text-align: justify;"}
Section 1: Introduction to Data Science: The Basics of Statistical Learning
:::


# Quiz {-}

```{js, echo=FALSE}
document.addEventListener('DOMContentLoaded', function() {
    var answers = document.querySelectorAll('.answers');

    answers.forEach(function(answer) {
        // Create the toggle button
        var button = document.createElement('button');
        button.className = 'toggle-answer-button';
        button.textContent = 'Show Answers'; // Updated text content
        button.style.display = 'block'; // Ensure button is visible
        answer.style.display = 'none'; // Initially hide the answer

        // Add click event listener to the button
        button.onclick = function() {
            if (answer.style.display === 'none') {
                answer.style.display = 'block'; // Show the answer
                button.textContent = 'Hide Answers'; // Update button text
            } else {
                answer.style.display = 'none'; // Hide the answer
                button.textContent = 'Show Answers'; // Reset button text
            }
        };

        // Insert the button before the answer
        answer.parentNode.insertBefore(button, answer);
    });
});

```


## Question 1: Flexible and Inflexible Methods {-}

For each of parts (a) through (d), indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.

(a) The sample size n is extremely large, and the number of predictors p is small.  

(b) The number of predictors p is extremely large, and the number of observations n is small.  

(c) The relationship between the predictors and response is highly non-linear.   

(d) The variance of the error terms is extremely high.  

::: answers
**(a) The sample size n is extremely large, and the number of predictors p is small.**  

Better - a more flexible approach will fit the data closer and with the large sample size a better fit than an inflexible approach would be obtained.  

**(b) The number of predictors p is extremely large, and the number of observations n is small.**   
Worse - a flexible method can cause overfit the small number of observations.So the overfitting model will result in a bigger inflation in variance and a small reduction in bias.  

**(c) The relationship between the predictors and response is highly non-linear.**  

better - with more degrees of freedom, a flexible model would obtain a better fit. A flexible model is better to find the non-linear effect. 

**(d) The variance of the error terms is extremely high.**  

worse - flexible methods would fit too much of the noise resulting from the large variance of the errors. 

*General Note:*  

- Fitting a more flexible model requires estimating a greater number of parameters.  
- With large sample sizes, there is less tendency for overfitting. However, there is a susceptibility to noise.  
:::

## Question 2: Regression and Classification Problems {-}

For each one of the scenarios below (a to c): 

- indicate whether the scenario is a *classification* or *regression* problem;  
- indicate whether we are most interested in inference or prediction;   
- describe the sample;  
- list the predictors (p).  

(a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.   

(b) We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price,and ten other variables.  

(c) We are interest in predicting the % change in the USD/Euro ed exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market. 

::: answers 

**(a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.**  

The scenario deals with a regression problem and we are interested in drawing inferences about the quantitative output of CEO salary based on CEO firm's characteristics. The sample constitutes 500 firms in the US and the independent variables are profit, number of employees, industry

**(b) We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price,and ten other variables.**  

The scenario deals with a classification problem and we are interested in predicting the success or failure of the new product. The sample constitutes 20 similar products previously launched and the independent variables are price charged, marketing budget, comp. price, and ten other variables.   

**(c) We are interest in predicting the % change in the USD/Euro ed exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. Foreach week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market.**   

The scenario deals with a regression problem and we are interested in predicting the quantitative output of percent change in the USD/Euro exchange rate in relation to the weekly changes in the world stock markets. The 'sample' constitutes 52 weeks of 2012 weekly data and the independent variables are % change in US market, % change in British market, % change in German market. 
:::

## Question 3: Flexibility in Regression and Classification {-}

What are the advantages and disadvantages of a very flexible (versus a less flexible) approach for regression or classification? Under what circumstances might a more flexible approach be preferred to a less flexible approach? When might a less flexible approach be preferred?

::: answers

**Flexible approaches**  

The advantages:  

1) obtaining a better fit for non-linear models;   
2) decreasing the error (bias).

The disadvantages:  

1) requires estimating a greater number of parameters;  
2) follow the noise too closely (overfit);  
3) increasing variance.

**The pros and cons for inflexible approaches are the opposite of those of flexible ones.**  

The flexible approach is preferred when we are interested in prediction and not the interpretability of the results (e.g. in cases where we have lots of data and many different groups).   

The inflexible approach when we are interested in inference and the interpretability of the results (e.g. when we do not have to deal of very large amounts of data).  

*Note*

For classification, an approach can be both flexible and less flexible. For highly flexible contexts, the training MSE is low but the test MSE is high, resulting in high variance. For more inflexible approaches, there is lower variance, but there is higher bias.  

Flexibility can be balanced using cross validation methods.
:::

## Question 4: Parametric and Non-parametric Methods {-}

Describe the differences between a parametric and a non-parametric statistical learning approach. What are the advantages of a parametric approach to regression or classification (as opposed to a non-parametric approach)? What are its disadvantages?  

::: answers
A parametric approach reduces the problem of estimating f down to one of estimating a set of parameters because it assumes a form for f. A non-parametric approach does not assume a functional form for f and so requires a very large number of observations to accurately estimate f.  

The advantages of a parametric approach to regression or classification are the simplifying of modeling f to a few parameters and not as many observations are required compared to a non-parametric approach. The disadvantages of a parametric approach to regression or classification are a potential to inaccurately estimate f if the form of f assumed is wrong or to overfit the observations if more flexible models are used.
:::

# Practical {-}