---
editor_options:
  markdown:
    wrap: 72
---

# Practical {-}

Loading the necessary packages: 

```{r warning = FALSE, message = FALSE}
library(ISLR2)
library(boot)
```

## Part I: The Validation Set Approach {-}

::: file
For the tasks below, you will require the **Default** dataset. This dataset is part of the `ISRL2` package from the core textbook (James et. al 2021). By loading the package, the **Default** dataset will load automatically. 
:::

The **Default** dataset contains 10,000 observations on four variables:   

- default: A factor with levels No and Yes indicating whether the customer defaulted on their debt  

- student: A factor with levels No and Yes indicating whether the customer is a student  

- balance:The average balance that the customer has remaining on their credit card after making their monthly payment  

- income: Income of customer   

In this exercise, we will use the validation set approach to estimate the test error of a logistic regression model that predicts the probability of credit card **default** using **income** and **balance**. 

### Task 1 {-}

Using the validation set approach, estimate the test error of this model following the guidance below: 

1. Split the sample set into a training set and a validation set (80/20)  
2. Fit a multiple logistic regression model using only the training observations.   
3. Obtain a prediction of default status for each individual in the validation set by computing the posterior probability of default for that individual, and classifying the individual to the default category if the posterior probability is greater than 0.5.  
4. Compute the validation set error, which is the fraction of the observations in the validation set that are misclassified.

*Don't forget that it is important to set a random seed before splitting the data and running the analysis, to obtain consistent results.*

### Task 2 {-}

Write a function that repeats the process above three times, using three different splits of the observations into a training set and a validation set. Comment on the results obtained. *Hint: use the base R function `replicate()`*.

### Task 3 {-}

Write a similar function as in Task 2, but this time include the variable **student** in the model. Comment on whether or not including a dummy variable for student leads to a reduction in the test error rate.

## Part II: Leave-one-out Cross-validation {-}

::: file
For the tasks below, you will require the **Weekly** dataset. This dataset is part of the `ISRL2` package from the core textbook (James et. al 2021). By loading the package, the **Default** dataset will load automatically. 
:::

The **Weekly** dataset contains 1,089 observations on nine variables. For the tasks in this section, you will require the variables below. For further information on the **Weekly** dataset, type `?Weekly` in your console after you load the `ISLR2` package.   

- Direction: A factor with levels Down and Up indicating whether the market had a positive or negative return on a given week  

- Lag1: Percentage return for previous week  

- Lag2: Percentage return for 2 weeks previous   

We will use the validation set approach to estimate the test error of a logistic regression model that predicts market movement (**Direction**) using percentage returns (**Lag1** and **Lag2**)

### Task 1 {-}

Fit a logistic regression model that predicts market movement using **Lag1** and **Lag2**

### Task 2 {-}

Use the model to predict the classification of the first observation. Was this observation correctly classified?
 
### Task 3 {-}

Write a for loop that performs each of the steps below: 

1. Fit a logistic regression model using all but the $i^{th}$ observation to predict **Direction** using **Lag1** and **Lag2**. 
2. Compute the posterior probability of upward market movement for the $i^{th}$ observation.
3. Use the posterior probability for the $i^{th}$ observation in order to predict whether or not there is upward market movement.
4. Determine whether or not an error was made in predicting the direction for the $i^{th}$ observation. If an error was made, then indicate this as a 1, and otherwise indicate it as a 0.


### Task 4 {-}

Obtain the LOOCV estimate for the test error. Comment on the results.

## Part III: The Bootstrap {-}

In this exercise, we return to our logistic regression model that predicts the probability of credit card **default** using **income** and **balance** and implement the bootstrap approach to compute estimates for the standard errors of the coefficients. 

### Task 1 {-}

Write a function called `boot.fn()`, that takes as input the Default data set as well as an index of the observations, and that outputs the coefficient estimates for income and balance in the multiple logistic regression model.


### Task 2 {-}

Use the `boot()` function together with the new `boot.fn()` function to estimate the standard errors of the logistic regression coefficients for income and balance. Comment on the estimated standard errors obtained using the `glm()` function and using your own bootstrap function.

## Bonus {-}

::: file
For the tasks below, you will require the **Boston** dataset. This dataset is part of the `ISRL2` package from the core textbook (James et. al 2021). By loading the package, the **Boston** dataset will load automatically. 
:::

### Task 1 {-}

Provide an estimate for the population mean of the **medv** variable which is the median value of owner-occupied homes. 

### Task 2 {-}

Provide an estimate of the standard error of  $\hat{\mu}$ and interpret the result. **Hint: You can compute the standard error of the sample mean by dividing the sample standard deviation by the square root of the number of observations.**
 
### Task 3 {-}

Now estimate the standard error of  $\hat{\mu}$ using the bootstrap. How does this compare to your answer from Task 2?

### Task 4 {-}

Based on your bootstrap estimate, provide a 95% confidence interval for the mean of medv. Compare it to the results obtained using `t.test(Boston$medv)`. Hint: You can approximate a 95% confidence interval using the formula  $[\hat{\mu}−2SE(\hat{\mu}),\hat{\mu} + 2SE(\hat{\mu})]$. 

### Task 5 {-}

Based on this data set, provide an estimate,  $\hat{\mu}_{med}$ for the median value of **medv** in the population.
 
### Task 6 {-}

Estimate the standard error of $\hat{\mu}_{med}$ using the bootstrap. Comment on your findings.
 
### Task 7 {-}

Based on this data set, provide an estimate for the tenth percentile of medv in Boston census tracts. Call this quantity  $\hat{\mu}_{0.1}$. *Hint: you can use the `quantile()` function.*
 
### Task 8 {-}

Use the bootstrap to estimate the standard error of  $\hat{\mu}_{0.1}$ and comment on your findings.
