# (PART\*) Section 4 {-}

# Overview {-}

<div style="color: #6D009D; font-size: 24px; font-weight: bold;text-align: justify;">
 Section 4: Reproducible Workflows with R Markdown
</div>

::: ilos
**Learning Outcomes:**

-   ADD ILOS.
:::

**In this section, you will practice how to use the following functions:**

|   Function    |               Description               | Package |
|:-------------:|:---------------------------------------:|:-------:|
|     `c()`     |          concatenate function           | base R  |

::: attention
**WARNING 1:** Before proceeding to the exercises, ensure that you create and work in a RStudio project and that you **write** and **save** your answers to the exercises in an R script.

**WARNING 2:** To adequately develop your practical programming skills, it is **essential** that you attempt all exercises by typing out the code rather than simply copy-pasting the answers.
:::

# Practical 1 {-}

## 1. Installing Git and GitHub Desktop {-}

1. Sign up with GitHub: https://github.com/ and explore the different options on the page. Your profile as well as your repositories can be accessed by clicking on the top right corner of the webpage.  

2. Install Git: https://git-scm.com/downloads. During installation, ensure that R and RStudio are not open. During the installation process, you will be prompted with many different options. Ensure that you continue the installation without changing any of the default options.  

3. Install the latest version of GitHub desktop: https://desktop.github.com/   

## 2. Connecting to GitHub with GitHub Desktop {-}

1. Open GitHub Desktop.    

2. Click on **File** from the menu at the top of the GitHub window, and select **Options**.   

3. A new window will open. Select **Accounts** and then click on **Sign in**. 
4. You will then be prompted to **Sign in Using Your Browser**. After clicking on **Continue With Browser**, GitHub Desktop will open in your default browser.   

5. You will then be prompted to **Sign in with GitHub to continue with GitHub Desktop**. Type in the details you have used to create the GitHub account and click on **Sign in**.  

**Your GitHub Desktop is now ready to use.**

## 3.Creating a Special Type of R project: the Version Control R Project

1. Create a new R Project in the same way as you have done before. 

2. Once your R project is ready, navigate to the Tools menu and select Version Control, then Project setup. 

3. You will be prompted by the Git/SVN dialogue box. Using the drop down menu from underneath Version Control System, change the NONE option to **Git**.

4. When asked if you want to initialise a new git repository for this project, click **YES**.  

5. When asked if you want to restart R project, click **YES**. 

6. Once RStudio reinitialises, you will see a new tab in the upper right hand corner next to Environment, History, Connections called **Git**. This is confirmation that you have connected your project with Git. Whilst working in this R Project, all new documents and changes to the files that you make will appear as a list under the Git tab and you can use this tab to make commits to the central repo. Keep your RStudio open for now. 

## 4. Creating a Repository and Connecting your Version Control Project {-}

1. Return to GitHub Desktop.  

2. Navigate to the File menu once again and select **New Repository**.  

3. In the Local Path, use the root working directory location of your newly created R project. A message will appear telling you that this directory appears to be a GitHub repository. You will also be asked if you want to add this repository instead. 

4. Click on the **add this repository instead** link. 

5. When prompted, click on **Create Repository**. By default, the repository will be set to private, meaning that others cannot see your repository unless given permission. 

6. Once GitHub creates your repository you will see several options. To publish your repository to the online GitHub platform, click on **Publish Repository**. When prompted, click on **Publish Repository** again. 

7. You should now be able to see your new repository both in the GitHub Desktop and online on the GitHub website. Explore both the GitHub desktop application and the GitHub website to familiarise yourself with the environment. You will also notice that a branch was created automatically; this means that everything that you change or add to your local project will be tracked and will be added to the central repository though commit actions. Since you own this repository, you cannot create a fork but you can create branches. 

*Optional: To create a new branch with GitHub Desktop, simply click on Current Branch and then select New Branch from the dialogue box. You will be asked whether you want to create a branch that is not dependent on your current branch or one that builds on the work done on the current branch. Depending on whether you want to start fresh work or whether you want to take a different development route to the work in your existing branch, GitHub is flexible. You can then switch between branches and even merge them.* 

For now, make sure to keep both the GitHub page and GitHub Desktop open (you can minimise them).

## 5. Adding New Files to your Repository

1. In your newly created R project, navigate to the New File icon, select R Markdown, then click on **From Template**. From the menu, select **GitHub Document (Markdown)** and click **Create**. 

2. Click on the **Knit** button. Once the process is complete, your file will appear in your root R project working directory. You will learn more about knitting and rendering documents in later lectures.

3. Now have a look at the Git tab. You should now see two files appear there, a file with the extension `.Rmd` file and one with the `.md` extension. These two files are accompanied by yellow symbols. This means that these files are not present in the repository and any changes that you make will only be saved on your computer hard drive. For now, do not perform any additional actions on these files. 

4. Now maximise the GitHub Desktop window. You should also see that these two new files have now appeared under the **Changes** tab.

5. At the moment, these two files are on your computer hard drive, in the R project working directory. To add them to your local repository, you must add them to the staging area and perform the **commit** actions. To then add these to the central repository you must also perform the **push** actions. You can do this either from RStudio directly or using GitHub Desktop (**although it is easier and faster if you commit and push using GitHub Desktop rather than RStudio**)  

### OPTION 1: With GitHub Desktop {-}

To perform the commit action with GitHub Desktop is very simple. The two files you created will now appear in the application and will have already been automatically selected (confirm that they are accompanied by check marks). In the Summary box underneath the files, provide a short description of these files and then click on **Commit to main**. Once the software reinitialises, click on **Push origin**. Note that if you do not click on **Push origin**, these files will NOT be added to the central repository but will only be updated in your local repository. After you perform the push action, you should no longer see these two files under the Changes tab but you can track the history of the changes made to this project by clicking on the **History** tab. 

If you now navigate to your online GitHub account page, you should see these two new files in your central remote repository (refresh the page if these are not visible). Click on the `.md` file to see how it is presented on GitHub. 

### OPTION 2: With RStudio {-}

To practice how to do this in RStudio, go back to your R Project and make sure that the Git tab is open; since you already performed the commit and push actions on the previous two files you created, the contents should be empty.  

Create a new R script, write some code, and save it. When the R script file appears in the Git tab, check the box next to the file. You will now notice that the status has 
changed to green which represents the action of adding the files to the staging area. To update these changes in your local repository, click **Commit**. when the dialogue box opens, you will notice that the overall format is similar to that of GitHub Desktop. The files are under the **Changes** tab, and all of the history of your actions can be seen in the History tab. 

Write a brief description of your files in the **Commit Message** box, and then click **Commit** again. The files will be updated in your local repository that you can access with GitHub Desktop application but will still not update the remote repository: to achieve this, you must then click on the **Push** button. RStudio will then connect with GitHub and you will see a confirmation that the files have been added to the remote repository in a new dialogue box (if prompted by a message asking you to grant access to Git, accept and proceed). To confirm this, simply go to your online GitHub or to GitHub Desktop. 

## 6. Modifying Existing Repository Files {-}

1. Return to your RStudio project and make sure that your Git tab is open. 

2. Make any change to your R script and save it. 

3. Now have a look at the contents of your Git tab. You should now see the file appear again but this time, the status is set to "Modified". This means that the system is detecting that this file already exists and it is being modified. If you have your GitHub Desktop open, you should see this change appear there also. 

4. To apply the changes made to the R script in the central repository, the same commit approach is used. As you have probably noticed, the GitHub Desktop approach to commit is slightly simpler and faster.  


**This practical is but an introduction to GitHub designed to prepare you with the necessary skills to create your own repository and publish your files and work on remote GitHub using RStudio and GitHub Desktop.**  

**If you want to learn more about how to use GitHub and GitHub Desktop collaboratively, visit: https://docs.github.com/en/desktop.**

# Practical 2 {-}

For this practical, you will be required to create a PDF Document using the built-in sample content provided by R Markdown.  

The R Markdown file you create should produce the following document: <a href="files_attached/DCVR_S04_Practical2.pdf" download="DCVR_S04_Practical2">click here to view the file</a>. You can view the file in your browser or save a copy on your computer. 

**In addition to carefully exploring the attached output, follow the guidelines below:**  

- Use numbered level 1 section headings  

- Set the font size to 10  

- Highlight the syntax using "haddock"  

- Set the figure width to 5 and figure height to 4 using the chunk options  

- Set the url colour to blue and the link color to orange  

- Load the `stargazer` package in a separate chunk and suppress the code and messages from showing in the output using chunk options.   

- Replace the `summary(cars)` code with linear model object as shown in the document.   

- Insert a new chunk and create a table with stargazer using the `model_A` object.  

- Customise the `plot(pressure)` output using chunk options so that the figure width is set to 5 and the figure height to 4. Also, align the output in the center of the page.  


:::attention
**AFTER** you have attempted this activity on your own, have a look at the original <a href="files_attached/DCVR_S04_Practical2.Rmd" download="DCVR_S04_Practical2">.Rmd file here</a>. You can view the file in your browser. If you want to save a copy, right-click on your mouse or keypad and select **Save as**. 
:::


