# (PART\*) Section 2 {.unnumbered}

# Overview {.unnumbered}

::: {style="color: #333; font-size: 24px; font-style: italic; text-align: justify;"}
Section 2: The Structure of Data Objects
:::

::: ilos
**Learning Outcomes:**

-   Differentiate between vectors, data frames, lists, and matrices;
-   Apply rules of various data structures to create different types of objects; 
-   Explore different types of data objects using suitable functions;
-   Calculate summary statistics; 
-   Make effective use of data dictionaries;
-   Perform basic transformation and recoding tasks using base R functions. 
:::

**In this section, you will be introduced to the following functions::**

|    Function    |                                        Description                                        | Package |
|:-------------:|:-----------------------------------------:|:-------------:|
|   `factor()`   |                                      create factors                                       | base R  |
| `data.frame()` |                                    create data frames                                     | base R  |
|    `list()`    |                                       create lists                                        | base R  |
|   `matrix()`   |                                      create matrices                                      | base R  |
|    `dim()`     |           find dimensions of object (e.g. number of variables and observations)           | base R  |
| `attributes()` |                         find attributes/characteristics of object                         | base R  |
|    `str()`     |                             view internal structure of object                             | base R  |
|   `table()`    |                                  build contingency table                                  | base R  |
|    `head()`    |                              view first parts of data object                              | base R  |
|    `tail()`    |                              view last parts of data object                               | base R  |
|  `colnames()`  |                  find or set row or column names of a matrix-like object                  | base R  |
|   `names()`    |                     find or set row or column names of a data object                      | base R  |
|  `summary()`   |                                 obtain summary statistics                                 | base R  |
|    `sum()`     |                                  obtain of sum of values                                  | base R  |
|   `is.na()`    | identifies NA values; returns a logical output (TRUE/FALSE) for each element in an object | base R  |

::: attention
Remember to continue working in the RStudio project you created for this course and typing your answers in separate R scripts. 
:::

# Practical 1 {.unnumbered}

<script>
document.addEventListener('DOMContentLoaded', function() {
    var codeBlocks = document.querySelectorAll('pre > code');

    codeBlocks.forEach(function(block) {
        // Check if the block's content starts with '##'
        if (block.textContent.trim().startsWith('##')) {
            var button = document.createElement('button');
            button.className = 'toggle-button';
            button.textContent = 'Show R Output';
            button.style.display = 'block'; // Ensure button is visible
            block.style.display = 'none'; // Initially hide the R output

            button.onclick = function() {
                if (block.style.display === 'none') {
                    block.style.display = 'block';
                    button.textContent = 'Hide R Output';
                } else {
                    block.style.display = 'none';
                    button.textContent = 'Show R Output';
                }
            };

            block.parentNode.insertBefore(button, block);
        }
    });
});
</script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var rComments = document.querySelectorAll('.r-comment');

    rComments.forEach(function(comment) {
        // Create the toggle button
        var button = document.createElement('button');
        button.className = 'toggle-comment-button';
        button.textContent = 'Show Explanation';
        button.style.display = 'block'; // Ensure button is visible
        comment.style.display = 'none'; // Initially hide the comment

        // Add click event listener to the button
        button.onclick = function() {
            if (comment.style.display === 'none') {
                comment.style.display = 'block'; // Adjust as needed
                button.textContent = 'Hide Explanation';
            } else {
                comment.style.display = 'none';
                button.textContent = 'Show Explanation';
            }
        };

        // Insert the button before the comment
        comment.parentNode.insertBefore(button, comment);
    });
});

</script>

## 1.1 Vectors and Factors {.unnumbered}

### 1.1.1 Exercise {.unnumbered}

Create and print a vector object named **data_vct** that contains the following values: 8, incorrect, 9.8.


```r
data_vct <- c(8, "incorrect", 9.8)

data_vct
```

```
## [1] "8"         "incorrect" "9.8"
```

::: question
What output does R produce? Why?
:::

::: {.r-comment style="display: none;"}
Vectors can only contain a single data type since they are homogenous structures and in this exercise, there are two data types in this vector, namely numeric and character. When R detects multiple data types within a vector, it will, by default, coerce all values to a single data type. Since the character value cannot be coerced to a numeric value, R will coerce all values to character. This is irrespective of whether the values are logical or numeric.\
Alternatively, if you did not place the word "incorrect" between inverted commas such as `data_vct <- c(8, incorrect, 9.8)`, then the attempt to create the vector would have failed and you would have been prompted by an error message: `Error: object 'incorrect' not found`. The reason for this is that only logical values can be specified as text in vectors without inverted commas; anything else will be a character value and must be specified within inverted commas.
:::

### 1.1.2 Exercise {.unnumbered}

Create a vector object named **data_vct2** that contains the following values: 8, FALSE, 9.8.


```r
data_vct2 <- c(8, FALSE, 9.8)

class(data_vct2)
```

```
## [1] "numeric"
```

::: question
What output does R produce? What class is this vector? Why?
:::

::: {.r-comment style="display: none;"}
This is another example of how R coerces values to have a consistent data type when detecting heterogeneity in a vector. In this case, the word FALSE must be specified as a logical value. This value is coerced to numeric because, by default, logical values in R are converted to 0 and 1, corresponding to FALSE and TRUE respectively. Alternatively, if you have specified the word FALSE as a character value, then the logical value would have been coerced to a character value and the vector would have been a vector of class `character`.
:::

### 1.1.3 Exercise {.unnumbered}

Create a vector object named **data_vct3** that contains the following values: 8, False, 9.8, True.


```r
data_vct3 <- c(8, False, 9.8, True)
```

```
## Error in eval(expr, envir, enclos): object 'False' not found
```

::: question
What output does R produce? Why?
:::

::: {.r-comment style="display: none;"}
If your treated this value as a logical value, then you would have obtained an error since logical values are case sensitive and can only take two different forms: `TRUE` or `T`, `FALSE` or `F`.
:::

### 1.1.4 Exercise {.unnumbered}

Create a factor named **data_fct** that contains the following values: bus, car, car, car, train, bus, bus, train, train. Print the contents, find the number of levels, and confirm the class.


```r
data_fct <- factor(c("bus", "car", "car", "car", 
                   "train", "bus", "bus", "train", "train"))

data_fct

class(data_fct)
```

::: {.r-comment style="display: none;"}
This object is of class `factor` and has three levels `bus, car, train`. The output should look like below:

data_fct

`[1] bus   car   car   car   train bus   bus   train train`\
`Levels: bus car train`

class(data_fct)

`[1] "factor"`
:::

### 1.1.5 Exercise {.unnumbered}

Create three vectors as follows:

-   A numeric vector called **num_vct** which contains the following values: 50, 10, 45, 90.

-   A character vector called **char_vct** which contains the following values: This, is, a, string, vector.

-   A logical vector called **logic_vct** which contains the following values: TRUE, FALSE, FALSE, TRUE, TRUE.


```r
num_vct <- c(50, 10, 45, 90)

char_vct <- c("This", "is", "a", "string", "vector")

logic_vct <- c(TRUE, FALSE, FALSE, TRUE, TRUE)
```

## 1.2 Data Frames and Lists {.unnumbered}

### 1.2.1 Exercise {.unnumbered}

Create a data frame called **df** by combing the following three vectors you previously created (**num_vct**, **char_vct**, **logic_vct**).


```r
df <- data.frame(num_vct, char_vct, logic_vct)
```

```
## Error in data.frame(num_vct, char_vct, logic_vct): arguments imply differing number of rows: 4, 5
```

::: question
What does the R output say? Why?
:::

::: {.r-comment style="display: none;"}
As you probably already noticed when finding the lengths of each vector earlier in the practical, the numeric vector has 4 rows whilst the character and logical vectors have 5 rows. When creating data frames, all vectors must have the same length, otherwise, you will be prompted by an error: `Error in data.frame(num_vct, char_vct, logic_vct) : arguments imply differing number of rows: 4, 5`.
:::

### 1.2.2 Exercise {.unnumbered}

Since a data frame cannot be created with vectors of different lengths, try to instead create a list object called **list_one** and print the contents.


```r
# Creating the list 
list_one <- list(num_vct, char_vct, logic_vct)

# Printing the list.
list_one
```

```
## [[1]]
## [1] 50 10 45 90
## 
## [[2]]
## [1] "This"   "is"     "a"      "string" "vector"
## 
## [[3]]
## [1]  TRUE FALSE FALSE  TRUE  TRUE
```

::: question
Did you successfully create a list? Why did this work (or didn't)?
:::

::: {.r-comment style="display: none;"}
The list was created successfully since lists are both heterogenous structures and can take different types of items regardless of their structure. No error message should appear.
:::

::: question
Can you find out how many variables and observations this list has? How about the number of items?
:::

::: {.r-comment style="display: none;"}
List structures do not have variables or observations since they are a storage mode of different types of items. Instead, lists are defined by the number of items they contain. If you print the contents, you can confirm that this list has 3 items.
:::

### 1.2.3 Exercise {.unnumbered}

Use the `View()` function to visualise the contents of the list you have just created. 


```r
View(list_one)
```

::: question
Is the output similar to that from a data frame object? Why not?
:::

::: {.r-comment style="display: none;"}
The `View()` function produces a different output for lists than in does for data frames since these are different structures. Data frames have rows and columns whilst lists have items. The view function is not very useful for lists because it is designed for users to visualise data values, but it does provide some relevant information such as the number of items, the data type of each item, and a compact summary of the values of each item.
:::

### 1.2.4 Exercise {.unnumbered}

Create a new vector called **num_vct3** with the following values: 50, 10, 45, 90, 5.


```r
num_vct3 <- c(50, 10, 45, 90, 5)
```

### 1.2.5 Exercise {.unnumbered}

Create a data frame called **df_one** by combing **num_vct3** with the following logical and character vectors you created earlier (**char_vct**, **logic_vct**). Then print the contents.


```r
df_one <- data.frame(num_vct3, char_vct, logic_vct)

df_one
```

```
##   num_vct3 char_vct logic_vct
## 1       50     This      TRUE
## 2       10       is     FALSE
## 3       45        a     FALSE
## 4       90   string      TRUE
## 5        5   vector      TRUE
```

::: question
How many variables and observations does this data frame have?
:::

::: {.r-comment style="display: none;"}
There are 5 observations of 3 variables. This is easy to identify with small data objects such as this one. For larger datasets, you can easily spot this by looking under the Environment tab.
:::

### 1.2.6 Exercise {.unnumbered}

Create a list called **list_two** by combining three of the vectors you created earlier (**num_vct3**, **num_vct**, **char_vct**, **logic_vct**).


```r
list_two <- list(num_vct3, num_vct, char_vct, logic_vct)
```

## 1.3 Matrices and Arrays {.unnumbered}

### 1.3.1 Exercise {.unnumbered}

Create and print a matrix named **matrix_one** that contains the following values: 1, 4, 6, 10. The values must be placed in two rows and two columns.


```r
matrix_one <- matrix(c(1,4,6,10), nrow = 2, ncol = 2)

matrix_one
```

```
##      [,1] [,2]
## [1,]    1    6
## [2,]    4   10
```

### 1.3.2 Exercise {.unnumbered}

Create and print a matrix named **matrix_two** that contains the following sequence of values: 10 to 13. The values must be placed in one row row and four columns.


```r
matrix_two <- matrix(10:13, nrow = 1, ncol = 4)
matrix_two
```

```
##      [,1] [,2] [,3] [,4]
## [1,]   10   11   12   13
```

### 1.3.3 Exercise {.unnumbered}

Create a matrix named **matrix_three** using the following numeric vector you created earlier (**num_vct**). The values must be placed in four rows and one column. Print the contents.


```r
matrix_three <- matrix(num_vct, nrow = 4, ncol = 1)

matrix_three
```

```
##      [,1]
## [1,]   50
## [2,]   10
## [3,]   45
## [4,]   90
```

## 1.4 Bonus Task {.unnumbered}

Create a list using the list of items below and name it **list_example**. Print the contents

-   **num_vct**
-   **matrix_three**
-   **df_one**
-   **list_two**
-   **"character string"**
-   **1000**


```r
list_example <- list(num_vct, matrix_three, df_one, 
                     list_two, "character string", 1000)

list_example
```

```
## [[1]]
## [1] 50 10 45 90
## 
## [[2]]
##      [,1]
## [1,]   50
## [2,]   10
## [3,]   45
## [4,]   90
## 
## [[3]]
##   num_vct3 char_vct logic_vct
## 1       50     This      TRUE
## 2       10       is     FALSE
## 3       45        a     FALSE
## 4       90   string      TRUE
## 5        5   vector      TRUE
## 
## [[4]]
## [[4]][[1]]
## [1] 50 10 45 90  5
## 
## [[4]][[2]]
## [1] 50 10 45 90
## 
## [[4]][[3]]
## [1] "This"   "is"     "a"      "string" "vector"
## 
## [[4]][[4]]
## [1]  TRUE FALSE FALSE  TRUE  TRUE
## 
## 
## [[5]]
## [1] "character string"
## 
## [[6]]
## [1] 1000
```

::: question
Is it possible for a list to contain any type of data structure and if so why? Can you find out how many items the list has?
:::

::: {.r-comment style="display: none;"}
Lists are highly flexible data structures and can contain any data type or object items, regardless of whether they are single values, or more complex structures. Lists also support nesting, which means that they can also contain other lists. There are 6 items in this list: a vector, a matrix, a data frame, a list, a character value, and a numeric value. This list is quite a large one and printing the contents is not a very useful way to view the items. You will learn alternatives functions to display data structures more compactly later in the course.
:::

# Practical 2 {.unnumbered}

<script>
document.addEventListener('DOMContentLoaded', function() {
    var codeBlocks = document.querySelectorAll('pre > code');

    codeBlocks.forEach(function(block) {
        // Check if the block's content starts with '##'
        if (block.textContent.trim().startsWith('##')) {
            var button = document.createElement('button');
            button.className = 'toggle-button';
            button.textContent = 'Show R Output';
            button.style.display = 'block'; // Ensure button is visible
            block.style.display = 'none'; // Initially hide the R output

            button.onclick = function() {
                if (block.style.display === 'none') {
                    block.style.display = 'block';
                    button.textContent = 'Hide R Output';
                } else {
                    block.style.display = 'none';
                    button.textContent = 'Show R Output';
                }
            };

            block.parentNode.insertBefore(button, block);
        }
    });
});
</script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var rComments = document.querySelectorAll('.r-comment');

    rComments.forEach(function(comment) {
        // Create the toggle button
        var button = document.createElement('button');
        button.className = 'toggle-comment-button';
        button.textContent = 'Show Explanation';
        button.style.display = 'block'; // Ensure button is visible
        comment.style.display = 'none'; // Initially hide the comment

        // Add click event listener to the button
        button.onclick = function() {
            if (comment.style.display === 'none') {
                comment.style.display = 'block'; // Adjust as needed
                button.textContent = 'Hide Explanation';
            } else {
                comment.style.display = 'none';
                button.textContent = 'Show Explanation';
            }
        };

        // Insert the button before the comment
        comment.parentNode.insertBefore(button, comment);
    });
});

</script>

## 2.1 Exploring Homogenous Data Structures {.unnumbered}

### 2.1.1 Exercise {.unnumbered}

Create the following vectors:

-   A numeric vector called **numeric_vct** comprising of: 8, 10, 5, 9, 6, 0, 2, 3.

-   A character vector called **char_vct** comprising of: bus, train, train, car, car, bus, train, bus.

-   A factor called **commuting** comprising of the same values as those of **char_vct**.

-   A factor called **commuting2** comprising of the same values as those of **commuting**. Use the levels argument to specify the following levels to the factor: bus, car, train, taxi.

-   A numeric vector called **num_vct** comprising of: 1, 2, 1, 3, 2, 3, 3, 1, 1, 2, 2, 4, 2, 4, 4. Transform this numeric vector into a factor called **education** and assign it the following labels: GCSE, Alevel, undergraduate, graduate.


```r
numeric_vector <- c(8, 10, 5, 9, 6, 0, 2, 3)

char_vct <- c("bus", "train", "train", "car", "car", "bus", "train", "bus")

commuting <- factor(char_vct)

commuting2 <- factor(char_vct, levels = c("bus", "car", "train", "taxi"))

num_vct <- c(1, 2, 1, 3, 2, 3, 3, 1, 1, 2, 2, 4, 2, 4, 4)
education <- factor(num_vct, labels  = c("GCSE", "Alevel", "undergraduate", "graduate"))
```

::: question
Explore **commuting** and **commuting2** using the `table()` function. How do the levels and number of observations of these two vectors differ?
:::


```r
table(commuting)

table(commuting2)
```

::: {.r-comment style="display: none;"}
The object values are of course identical for levels **bus**, **car**, and **train** but you have also added one more level to **commuting2**, namely **taxi**. As you would have seen in the output in your RStudio console, there are zero observations for this factor level.

`> table(commuting2)`\
`bus   car train  taxi`\
`3     2     3     0`

Versus

`> table(commuting)`\
`bus   car train`\
`3     2     3`

This illustrates that levels can be added to factors even though observations for that particular level are not present in the 'dataset'. This is an important feature of factors during statistical analysis since the absence of data is meaningful for categorical variables.
:::

### 2.1.2 Exercise {.unnumbered}

Create a matrix object called **matrix_object** using one of the numeric vectors you created earlier (**numeric_vector**). The matrix must have 2 rows and 4 columns.


```r
matrix_object <- matrix(numeric_vector, nrow = 2, ncol = 4)
```

Find the class, length, and dimensions.


```r
class(matrix_object)
```

```
## [1] "matrix" "array"
```

```r
length(matrix_object)
```

```
## [1] 8
```

```r
dim(matrix_object)
```

```
## [1] 2 4
```

\newpage

## 2.2 Exploring Heterogenous Data Structures {.unnumbered}

### Exercise 2.2.1 {.unnumbered}

Create a data frame called **data_frame** by combining the three objects you created earlier (**numeric_vector**, **char_vct**, and **commuting**).


```r
data_frame <- data.frame(numeric_vector, char_vct, commuting)
```

Find the class, dimensions and attributes.


```r
class(data_frame)
```

```
## [1] "data.frame"
```

```r
dim(data_frame)
```

```
## [1] 8 3
```

```r
attributes(data_frame)
```

```
## $names
## [1] "numeric_vector" "char_vct"       "commuting"     
## 
## $class
## [1] "data.frame"
## 
## $row.names
## [1] 1 2 3 4 5 6 7 8
```

### Exercise 2.2.2 {.unnumbered}

Compactly view the first and last parts of the **data_frame** object.


```r
head(data_frame)
```

```
##   numeric_vector char_vct commuting
## 1              8      bus       bus
## 2             10    train     train
## 3              5    train     train
## 4              9      car       car
## 5              6      car       car
## 6              0      bus       bus
```


```r
tail(data_frame)
```

```
##   numeric_vector char_vct commuting
## 3              5    train     train
## 4              9      car       car
## 5              6      car       car
## 6              0      bus       bus
## 7              2    train     train
## 8              3      bus       bus
```

### Exercise 2.2.3 {.unnumbered}

Find the names of the columns of **data_frame**.


```r
colnames(data_frame)
```

```
## [1] "numeric_vector" "char_vct"       "commuting"
```

```r
# OR

names(data_frame)
```

```
## [1] "numeric_vector" "char_vct"       "commuting"
```

### Exercise 2.2.4 {.unnumbered}

Create a list called **list_combined** by combining the following objects you previously created (**numeric_vector**, **commuting**, **education**, and **data_frame**).


```r
list_combined <- list(numeric_vector, commuting, education, data_frame)
```

### Exercise 2.2.5 {.unnumbered}

View the contents of **list_combined** in a compact form.


```r
str(list_combined)
```

```
## List of 4
##  $ : num [1:8] 8 10 5 9 6 0 2 3
##  $ : Factor w/ 3 levels "bus","car","train": 1 3 3 2 2 1 3 1
##  $ : Factor w/ 4 levels "GCSE","Alevel",..: 1 2 1 3 2 3 3 1 1 2 ...
##  $ :'data.frame':	8 obs. of  3 variables:
##   ..$ numeric_vector: num [1:8] 8 10 5 9 6 0 2 3
##   ..$ char_vct      : chr [1:8] "bus" "train" "train" "car" ...
##   ..$ commuting     : Factor w/ 3 levels "bus","car","train": 1 3 3 2 2 1 3 1
```

::: question
What does the output tell you about **list_combined**?
:::

::: {.r-comment style="display: none;"}
The `str()` function provides the total number of items in an object (in this case a list), the class of each item, as well as the number of elements within each item. There are 4 items; in the order in which they would appear in your console, these are: a numeric vector of 8 elements, a factor with 3 levels, a factor with 4 levels, and a data frame composed of a numeric, character, and factor.
:::

# Practical 3 {.unnumbered}

<script>
document.addEventListener('DOMContentLoaded', function() {
    var codeBlocks = document.querySelectorAll('pre > code');

    codeBlocks.forEach(function(block) {
        // Check if the block's content starts with '##'
        if (block.textContent.trim().startsWith('##')) {
            var button = document.createElement('button');
            button.className = 'toggle-button';
            button.textContent = 'Show R Output';
            button.style.display = 'block'; // Ensure button is visible
            block.style.display = 'none'; // Initially hide the R output

            button.onclick = function() {
                if (block.style.display === 'none') {
                    block.style.display = 'block';
                    button.textContent = 'Hide R Output';
                } else {
                    block.style.display = 'none';
                    button.textContent = 'Show R Output';
                }
            };

            block.parentNode.insertBefore(button, block);
        }
    });
});
</script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var rComments = document.querySelectorAll('.r-comment');

    rComments.forEach(function(comment) {
        // Create the toggle button
        var button = document.createElement('button');
        button.className = 'toggle-comment-button';
        button.textContent = 'Show Explanation';
        button.style.display = 'block'; // Ensure button is visible
        comment.style.display = 'none'; // Initially hide the comment

        // Add click event listener to the button
        button.onclick = function() {
            if (comment.style.display === 'none') {
                comment.style.display = 'block'; // Adjust as needed
                button.textContent = 'Hide Explanation';
            } else {
                comment.style.display = 'none';
                button.textContent = 'Show Explanation';
            }
        };

        // Insert the button before the comment
        comment.parentNode.insertBefore(button, comment);
    });
});

</script>

## 3.1 Exploring Data Files {.unnumbered}

In Section 1, you have completed a series of file import/export exercises using data from *British Social Attitudes Survey (2019): Open Access Teaching Dataset.* 

::: reference
British Social Attitudes Survey, 2019, Poverty and Welfare: Open Access Teaching Dataset

*Reference*  

University of Manchester, Cathie Marsh Institute for Social Research (CMIST), UK Data Service. (2022). British Social Attitudes Survey, 2019, Poverty and Welfare: Open Access Teaching Dataset. [data collection]. NatCen Social Research, [original data producer(s)]. NatCen Social Research. SN: 8850, DOI: http://doi.org/10.5255/UKDA-SN-8850-1  

*Copyright*  

Data download and access under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International </a> licence.
::: 


For this practical, you will use one of the objects you have exported as a `.csv` file in your R project **data** folder, namely the **bsas_stata** object.  


### 3.1.1 Exercise {.unnumbered}

Import the **bsas_stata** `.csv` object and name this object **bsas_dataset**.





```r
bsas_dataset <- read.csv("data/bsas_stata_file.csv")
```

::: question
Explore the structure of the data object and confirm its class. How many observations and variables does this object have?
:::

::: {.r-comment style="display: none;"}
Use the `class()` function to confirm that the data object is a `data.frame`. You can explore the structure of the object in various ways such as using the `str()` function which also tells you the number of observations and variables. You can also, of course, obtain this information from your **Environment** pane.
:::

### 3.1.2 Exercise {.unnumbered}

Obtain a compact summary statistics output.


```r
summary(bsas_dataset)
```

```
##        X             Sserial          WtFactor           RSex      
##  Min.   :   1.0   Min.   :310001   Min.   :0.2950   Min.   :1.000  
##  1st Qu.: 806.8   1st Qu.:310807   1st Qu.:0.5865   1st Qu.:1.000  
##  Median :1612.5   Median :311613   Median :0.9042   Median :2.000  
##  Mean   :1612.5   Mean   :311613   Mean   :1.0000   Mean   :1.549  
##  3rd Qu.:2418.2   3rd Qu.:312418   3rd Qu.:1.2064   3rd Qu.:2.000  
##  Max.   :3224.0   Max.   :313224   Max.   :4.4400   Max.   :2.000  
##     RAgeCat      eq_inc_quintiles    RClassGp         HEdQual3   
##  Min.   :1.000   Min.   :-1.000   Min.   :-1.000   Min.   :1.00  
##  1st Qu.:3.000   1st Qu.:-1.000   1st Qu.: 1.000   1st Qu.:2.00  
##  Median :4.000   Median : 2.000   Median : 2.000   Median :2.00  
##  Mean   :4.569   Mean   : 1.874   Mean   : 2.722   Mean   :2.56  
##  3rd Qu.:7.000   3rd Qu.: 4.000   3rd Qu.: 5.000   3rd Qu.:3.00  
##  Max.   :8.000   Max.   : 5.000   Max.   : 8.000   Max.   :8.00  
##     Married         ChildHh        skipmeal          paptype     
##  Min.   :1.000   Min.   :1.00   Min.   :-1.0000   Min.   :0.000  
##  1st Qu.:1.000   1st Qu.:1.00   1st Qu.:-1.0000   1st Qu.:0.000  
##  Median :1.000   Median :2.00   Median : 1.0000   Median :0.000  
##  Mean   :2.036   Mean   :1.68   Mean   : 0.4935   Mean   :0.348  
##  3rd Qu.:3.000   3rd Qu.:2.00   3rd Qu.: 1.0000   3rd Qu.:0.000  
##  Max.   :9.000   Max.   :2.00   Max.   : 9.0000   Max.   :8.000  
##      SMNews          PartyId2        Politics        SocTrust      
##  Min.   : 1.000   Min.   :-1.00   Min.   :1.000   Min.   :-1.0000  
##  1st Qu.: 2.000   1st Qu.: 1.00   1st Qu.:2.000   1st Qu.:-1.0000  
##  Median : 8.000   Median : 2.00   Median :3.000   Median :-1.0000  
##  Mean   : 5.636   Mean   : 3.04   Mean   :2.869   Mean   :-0.1051  
##  3rd Qu.: 8.000   3rd Qu.: 5.00   3rd Qu.:4.000   3rd Qu.: 1.0000  
##  Max.   :98.000   Max.   : 8.00   Max.   :9.000   Max.   : 8.0000  
##      Spend1             Dole          TaxSpend        MuchPov    
##  Min.   :-1.0000   Min.   :1.000   Min.   :1.000   Min.   :1.00  
##  1st Qu.:-1.0000   1st Qu.:1.000   1st Qu.:2.000   1st Qu.:1.00  
##  Median :-1.0000   Median :2.000   Median :3.000   Median :2.00  
##  Mean   : 0.6845   Mean   :2.303   Mean   :2.676   Mean   :1.97  
##  3rd Qu.: 3.0000   3rd Qu.:3.000   3rd Qu.:3.000   3rd Qu.:2.00  
##  Max.   :98.0000   Max.   :9.000   Max.   :9.000   Max.   :9.00  
##     Poverty1        Poverty2       NatFrEst        incdiffs      
##  Min.   :1.000   Min.   :1.00   Min.   :  0.0   Min.   :-1.0000  
##  1st Qu.:1.000   1st Qu.:1.00   1st Qu.: 12.0   1st Qu.:-1.0000  
##  Median :2.000   Median :1.00   Median : 35.0   Median : 1.0000  
##  Mean   :1.865   Mean   :1.56   Mean   :109.2   Mean   : 0.7382  
##  3rd Qu.:2.000   3rd Qu.:2.00   3rd Qu.: 60.0   3rd Qu.: 2.0000  
##  Max.   :9.000   Max.   :8.00   Max.   :999.0   Max.   : 9.0000  
##     welfare2         leftrigh         libauth      
##  Min.   :-1.000   Min.   :-1.000   Min.   :-1.000  
##  1st Qu.: 1.875   1st Qu.: 1.600   1st Qu.: 2.500  
##  Median : 2.625   Median : 2.400   Median : 3.333  
##  Mean   : 2.156   Mean   : 2.006   Mean   : 2.797  
##  3rd Qu.: 3.125   3rd Qu.: 3.000   3rd Qu.: 4.000  
##  Max.   : 9.000   Max.   : 9.000   Max.   : 9.000
```

::: question
Do you think all of these variables are actually numeric? Why?
:::

::: {.r-comment style="display: none;"}
No; variables in survey datasets are often coded in numeric form, regardless of whether these are actually numeric or categorical. Datasets from reputable sources such as the UK Data Service (UKDS), are accompanied by data dictionaries which describe and explain in detail what each variable measures and how it is coded in the data file. For data that you download from the UKDS, the data dictionary can be found in the **mrdoc** folder.

In general, datasets from the UKDS will be available in a format that hosts metadata (e.g. Stata, SPSS). This means that if you explore the variables in a SPSS or Stata data file you imported in R, you will note that variables are accompanied by metadata. Those which are categorical are also accompanied by labels which describe the categories to which numeric values belong. However, since you are now using the file you exported as a `.csv`, you will remember that such files do not host any metadata.
:::

### 3.1.3 Exercise {.unnumbered}

To practice using data dictionaries, open the **mrdoc** subfolder within the main folder you downloaded for the Stata file (**UKDA-8850-stata**). Extract the file from the zippeed **ukda_data_dictionaries** folder.

Find the following variables in the data dictionary: **NatFrEst**, **RSex**, **Married**, and **RAgeCat**.

::: question
What do these variables measure and how are they coded?
:::

::: {.r-comment style="display: none;"}
According to the data dictionary:

-   **NatFrEst** asks survey respondents to provide an estimated numeric value for the following question: *Out of every 100 people receiving benefits in Britain, how many have broken the law by giving false information to support their claim?*.\
-   **RSex** represents the sex of the respondent. Males are numerically labelled as "1" and females as "2".\
-   **Married** represents the marital status of the respondent. There are four categories labelled "1" to "4".\
-   **RAgeCat** represents the age category into which the respondent falls. Age is grouped into 7 categories labelled "1" to "7".\
:::

## 3.2 Subsetting {.unnumbered}

### 3.2.1 Exercise {.unnumbered}

Create a new data frame object called **bsas_sample** that contains the following variables in this order: NatFrEst, RSex, Married, and RAgeCat.


```r
bsas_sample <- bsas_dataset[c("NatFrEst", "RSex", "Married", "RAgeCat")]
```

::: {.r-comment style="display: none;"}
As you have already seen in the lecture materials, there are various ways to achieve this. One simple way is to specify a character vector of variable names using `c()` within square brackets used to subset a data object.
:::

### 3.2.2 Exercise {.unnumbered}

Find the class of variable **Married**.


```r
class(bsas_sample$Married)
```

```
## [1] "integer"
```

::: question
Would you be able to analyse this variable as it is, without any further transformation?
:::

::: {.r-comment style="display: none;"}
In most cases, the answer would be NO, since this variable is categorical and should be coded as a factor. If you also explore RSex and RAgeCat, you would also see that they are also of class `integer`. To ensure that you recode all relevant variables correctly, you must consult the data dictionaries.
:::

## 3.3 Basic Transformations {.unnumbered}

### 3.3.1 Exercise {.unnumbered}

Use `colnames()` function to change the names of the variables as follows:

-   NatFrEst to false_benefits
-   RSex to sex
-   Married to marital_status
-   RAgeCat to age_cat


```r
colnames(bsas_sample) <- c("false_benefits", "sex", "marital_status", "age_category")
```

Now confirm that the column names have been changed.


```r
colnames(bsas_sample)
```

```
## [1] "false_benefits" "sex"            "marital_status" "age_category"
```

```r
# You can use the same function or, more simply:

# names(bsas_sample)
```

### 3.3.2 Exercise {.unnumbered}

Using the `table()` function, explore the contents of the variable **false_benefits**.


```r
table(bsas_sample$false_benefits)
```

```
## 
##   0   1   2   3   4   5   6   7   8   9  10  12  13  15  18  19  20  23  25  27 
##   8  68  82  43  25 192   3  14  10   1 354   7   1  90   1   1 286   1 190   3 
##  30  32  33  35  38  40  42  43  45  46  47  48  49  50  51  55  56  57  59  60 
## 194   2  19  45   1 188   1   3  23   2   1   2   1 436   2  20   1   2   1 160 
##  63  65  66  68  69  70  75  78  79  80  82  85  86  88  90  93  95  98  99 100 
##   1  29   2   2   2 107  77   2   1 126   2  18   1   2  58   1  10   4  19  30 
## 998 999 
## 242   4
```

::: question
Are there any strange values and if so, what do they mean?
:::

::: {.r-comment style="display: none;"}
Based on the data dictionary you have consulted in the previous exercise, you should already know that each one of the four variables, regardless of whether it is measured on a numeric or nominal scale, has labels that denote missing data. For the variable **false_benefits**, there are several missing data since both 998 and 999 labels appear in the table. This type of information is very important for recoding/transforming variables correctly.
:::

### 3.3.3 Exercise {.unnumbered}

Perform the following modifications to the variables below:

-   For marital_status, change the 9 values to `NA`.\
-   For age_category , change the 8 values to `NA`.\
-   For false_benefits, change the 998 and 999 values to `NA`.


```r
bsas_sample$marital_status[bsas_sample$marital_status == 9] <- NA

bsas_sample$age_category[bsas_sample$age_category == 8] <- NA

bsas_sample$false_benefits[bsas_sample$false_benefits > 900] <- NA
```

::: {.r-comment style="display: none;"}
For the false_benefits variable, the simplest approach is to specify a value large enough to encompass both 998 and 999. In this case, the maximum value is 100 after which there are no values corresponding to any number between 100 and 998.
:::

::: question
How many `NA` values does the variable **false_benefits** have in total?
:::


```r
sum(is.na(bsas_sample$false_benefits))
```

```
## [1] 246
```

### 3.3.4 Exercise {.unnumbered}

For the **sex** variable, change the 1 values to Male and the 2 values to Female.


```r
bsas_sample$sex[bsas_sample$sex == 1] <- "Male"

bsas_sample$sex[bsas_sample$sex == 2 ] <- "Female"
```

::: {.r-comment style="display: none;"}
For the purposes of this practical, it is acceptable to perform factor recoding for each category individually. You will learn how to do this more efficiently later in in the course.
:::

Now confirm the changes using a suitable function.


```r
table(bsas_sample$sex)
```

```
## 
## Female   Male 
##   1770   1454
```

::: question
What is the class of the variable now?
:::


```r
class(bsas_sample$sex)
```

```
## [1] "character"
```

::: {.r-comment style="display: none;"}
After changing the numeric labels to character labels, the variable is now of class `character`. To make this variable a factor, we need an extra step:\
`bsas_sample$sex <- factor(bsas_sample$sex)`.
:::

### 3.3.5 Exercise {.unnumbered}

Create a new vector object called **id** that contains a sequence of values from 1 to 3,224.


```r
id <- 1:3224
```

Add **id** as a column to the **bsas_sample** data frame.


```r
bsas_sample$id <- id
```

::: question
Where in the data frame was **id** added?
:::


```r
str(bsas_sample)
```

```
## 'data.frame':	3224 obs. of  5 variables:
##  $ false_benefits: int  5 30 50 50 50 10 1 NA 5 50 ...
##  $ sex           : chr  "Female" "Female" "Female" "Male" ...
##  $ marital_status: int  1 2 1 4 4 1 4 1 1 4 ...
##  $ age_category  : int  6 3 4 2 6 4 2 4 4 1 ...
##  $ id            : int  1 2 3 4 5 6 7 8 9 10 ...
```

::: {.r-comment style="display: none;"}
You can find this out in various ways, one being `str()`. The new column was added at the **end** of the data frame. The purpose of adding an ID column is to uniquely identify each case within the data frame (in cases where no such ID exists). You will learn more about why this is important, later in the course.
:::

### 3.3.6 Exercise {.unnumbered}

Reorder the variables of **bsas_sample** as follows: id, RSex, RAgeCat, Married, and NatFrEst.


```r
bsas_sample <- bsas_sample[, c("id", "sex", "age_category", "marital_status", "false_benefits")]
```

Confirm the change in order using a suitable function.


```r
# You can use the names() function, for example. 

names(bsas_sample)
```

```
## [1] "id"             "sex"            "age_category"   "marital_status"
## [5] "false_benefits"
```
