<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Answers | Data Science Modelling</title>
  <meta name="description" content="Notebook hosting practical materials for SOST70033." />
  <meta name="generator" content="bookdown 0.38 and GitBook 2.6.7" />

  <meta property="og:title" content="Answers | Data Science Modelling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notebook hosting practical materials for SOST70033." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Answers | Data Science Modelling" />
  
  <meta name="twitter:description" content="Notebook hosting practical materials for SOST70033." />
  

<meta name="author" content="Dr. Ioana Macoveciuc" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="practical-predicting-a-companys-bankruptcy.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/logos/uom_logo.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="part"><span><b>Section 1</b></span></li>
<li class="chapter" data-level="" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-a-more-in-depth-consideration-of-model-accuracy.html"><a href="demonstration-a-more-in-depth-consideration-of-model-accuracy.html"><i class="fa fa-check"></i>Demonstration: A more in-depth consideration of model accuracy</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-a-more-in-depth-consideration-of-model-accuracy.html"><a href="demonstration-a-more-in-depth-consideration-of-model-accuracy.html#the-simulation"><i class="fa fa-check"></i>The Simulation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-1"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-2"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-3"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-4"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-5"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-6"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-7"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-8"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-9"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-10"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-11"><i class="fa fa-check"></i>Task 11</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-1-1"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-2-1"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-3-1"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-4-1"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-5-1"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-6-1"><i class="fa fa-check"></i>Task 6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html"><i class="fa fa-check"></i>Answers</a>
<ul>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#practical-1-1"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-1-2"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-2-2"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-3-2"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-4-2"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-5-2"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-6-2"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-7-1"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-8-1"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-9-1"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-10-1"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-11-1"><i class="fa fa-check"></i>Task 11</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#practical-2-1"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-1-3"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-2-3"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-3-3"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-4-3"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-5-3"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-6-3"><i class="fa fa-check"></i>Task 6</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Section 2</b></span></li>
<li class="chapter" data-level="" data-path="overview-1.html"><a href="overview-1.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-1.html"><a href="demonstration-1.html"><i class="fa fa-check"></i>Demonstration 1</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1.html"><a href="demonstration-1.html#simple-linear-models-without-intercept"><i class="fa fa-check"></i>Simple Linear Models Without Intercept</a></li>
<li class="chapter" data-level="" data-path="demonstration-1.html"><a href="demonstration-1.html#simple-linear-models-with-intercept"><i class="fa fa-check"></i>Simple Linear Models with Intercept</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html"><i class="fa fa-check"></i>Demonstration 2</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#population-parameters-and-estimated-coefficients"><i class="fa fa-check"></i>Population Parameters and Estimated Coefficients</a></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#what-happens-if-we-reduce-noise"><i class="fa fa-check"></i>What happens if we <em>reduce</em> noise?</a></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#what-happens-if-we-increase-noise"><i class="fa fa-check"></i>What happens if we <em>increase</em> noise?</a></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#how-does-noise-affect-confidence-intervals-for-the-coefficients"><i class="fa fa-check"></i>How does noise affect confidence intervals for the coefficients?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-1-4"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-2-4"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-3-4"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-4-4"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-5-4"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-6-4"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-7-2"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-8-2"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-9-2"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-10-2"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-11-2"><i class="fa fa-check"></i>Task 11</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-12"><i class="fa fa-check"></i>Task 12</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-13"><i class="fa fa-check"></i>Task 13</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-14"><i class="fa fa-check"></i>Task 14</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-15"><i class="fa fa-check"></i>Task 15</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-16"><i class="fa fa-check"></i>Task 16</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-1-5"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-2-5"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-3-5"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-4-5"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-5-5"><i class="fa fa-check"></i>Task 5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-3-the-quality-of-red-bordeaux-vintages.html"><a href="practical-3-the-quality-of-red-bordeaux-vintages.html"><i class="fa fa-check"></i>Practical 3: The Quality of Red Bordeaux Vintages</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html"><i class="fa fa-check"></i>Answers</a>
<ul>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#practical-1-3"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-1-6"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-2-6"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-3-6"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-4-6"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-5-6"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-6-5"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-7-3"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-8-3"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-9-3"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-10-3"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-11-3"><i class="fa fa-check"></i>Task 11</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-12-1"><i class="fa fa-check"></i>Task 12</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-13-1"><i class="fa fa-check"></i>Task 13</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-14-1"><i class="fa fa-check"></i>Task 14</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-15-1"><i class="fa fa-check"></i>Task 15</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-16-1"><i class="fa fa-check"></i>Task 16</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#practical-2-3"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-1-7"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-2-7"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-3-7"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-4-7"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-5-7"><i class="fa fa-check"></i>Task 5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#practical-3-the-quality-of-red-bordeaux-vintages-1"><i class="fa fa-check"></i>Practical 3: The Quality of Red Bordeaux Vintages</a></li>
</ul></li>
<li class="part"><span><b>Section 3</b></span></li>
<li class="chapter" data-level="" data-path="overview-2.html"><a href="overview-2.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html"><i class="fa fa-check"></i>Demonstration 1: Classification Problems</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#dataset-and-variables"><i class="fa fa-check"></i>Dataset and Variables</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#correlation-matrix-and-plot"><i class="fa fa-check"></i>Correlation Matrix and Plot</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#classic-logistic-regression"><i class="fa fa-check"></i>“Classic” Logistic Regression</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#confusion-matrix"><i class="fa fa-check"></i>Confusion Matrix</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#logistic-regression-in-statistical-learning"><i class="fa fa-check"></i>Logistic Regression in Statistical Learning</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#linear-discriminant-analysis"><i class="fa fa-check"></i>Linear Discriminant Analysis</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#quadratic-discriminant-analysis"><i class="fa fa-check"></i>Quadratic Discriminant Analysis</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#k-nearest-neighbours"><i class="fa fa-check"></i><span class="math inline">\(K\)</span>-nearest neighbours</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-classification-problems.html"><a href="demonstration-1-classification-problems.html#naive-bayes"><i class="fa fa-check"></i>Naive Bayes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-2-poisson-versus-linear-regression.html"><a href="demonstration-2-poisson-versus-linear-regression.html"><i class="fa fa-check"></i>Demonstration 2: Poisson versus Linear Regression</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-2-poisson-versus-linear-regression.html"><a href="demonstration-2-poisson-versus-linear-regression.html#the-linear-model"><i class="fa fa-check"></i>The Linear Model</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-2-poisson-versus-linear-regression.html"><a href="demonstration-2-poisson-versus-linear-regression.html#approaches-to-variable-coding"><i class="fa fa-check"></i>Approaches to variable coding</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-poisson-versus-linear-regression.html"><a href="demonstration-2-poisson-versus-linear-regression.html#plotting-coefficient-estimates"><i class="fa fa-check"></i>Plotting Coefficient Estimates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-2-poisson-versus-linear-regression.html"><a href="demonstration-2-poisson-versus-linear-regression.html#the-poisson-model"><i class="fa fa-check"></i>The Poisson Model</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-poisson-versus-linear-regression.html"><a href="demonstration-2-poisson-versus-linear-regression.html#linear-versus-poisson-regression"><i class="fa fa-check"></i>Linear versus Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html"><i class="fa fa-check"></i>Practical: Predicting a company’s bankruptcy</a>
<ul>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#data-and-variables"><i class="fa fa-check"></i>Data and Variables</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#importing-the-data"><i class="fa fa-check"></i>Importing the data</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#loading-required-packages"><i class="fa fa-check"></i>Loading required packages</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#correlation-matrix-and-plot-1"><i class="fa fa-check"></i>Correlation Matrix and Plot</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#logistic-regression"><i class="fa fa-check"></i>Logistic Regression</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#explaining-the-logit"><i class="fa fa-check"></i>Explaining the Logit</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#tasks-linear-discriminant-analysis"><i class="fa fa-check"></i>Tasks: Linear Discriminant Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-1-8"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-2-8"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-3-8"><i class="fa fa-check"></i>Task 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#tasks-quadratic-discriminant-analysis"><i class="fa fa-check"></i>Tasks: Quadratic Discriminant Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-1-9"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-2-9"><i class="fa fa-check"></i>Task 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#tasks-k-nearest-neighbours"><i class="fa fa-check"></i>Tasks: <span class="math inline">\(K\)</span>-nearest neighbours</a>
<ul>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-1-10"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-2-10"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-3-9"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-4-8"><i class="fa fa-check"></i>Task 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#tasks-naive-bayes"><i class="fa fa-check"></i>Tasks: Naive Bayes</a>
<ul>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-1-11"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-predicting-a-companys-bankruptcy.html"><a href="practical-predicting-a-companys-bankruptcy.html#task-2-11"><i class="fa fa-check"></i>Task 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html"><i class="fa fa-check"></i>Answers</a>
<ul>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#practical-predicting-a-companys-bankruptcy-1"><i class="fa fa-check"></i>Practical: Predicting a company’s bankruptcy</a>
<ul>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#data-and-variables-1"><i class="fa fa-check"></i>Data and Variables</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#importing-the-data-1"><i class="fa fa-check"></i>Importing the data</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#loading-required-packages-1"><i class="fa fa-check"></i>Loading required packages</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#correlation-matrix-and-plot-2"><i class="fa fa-check"></i>Correlation Matrix and Plot</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#logistic-regression-1"><i class="fa fa-check"></i>Logistic Regression</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#linear-discriminant-analysis-1"><i class="fa fa-check"></i>Linear Discriminant Analysis</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#quadratic-discriminant-analysis-1"><i class="fa fa-check"></i>Quadratic Discriminant Analysis</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#k-nearest-neighbours-1"><i class="fa fa-check"></i><span class="math inline">\(K\)</span>-nearest neighbours</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#naive-bayes-1"><i class="fa fa-check"></i>Naive Bayes</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science Modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<hr>
<center> 
  <div class="header">
   <img src="images/banners/DSM_banner.png" alt="Trulli">
  </div>
</center>
<div id="answers-2" class="section level1 unnumbered hasAnchor">
<h1>Answers<a href="answers-2.html#answers-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="practical-predicting-a-companys-bankruptcy-1" class="section level2 unnumbered hasAnchor">
<h2>Practical: Predicting a company’s bankruptcy<a href="answers-2.html#practical-predicting-a-companys-bankruptcy-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>This practical is adapted from a demonstration created by Dr. Tatjana Kecojevic, Lecturer in Social Statistics.</em></p>
<div class="file">
<p>For the tasks below, you will require the <strong>four_ratios</strong> dataset.</p>
<p>Click here to download the file:
<a href="data/four_ratios.csv" download="four_ratios.csv"> four_ratios.csv </a>.</p>
<p>Remember to place your data file in a separate subfolder within your R
project working directory.</p>
</div>
<div id="data-and-variables-1" class="section level3 unnumbered hasAnchor">
<h3>Data and Variables<a href="answers-2.html#data-and-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In order to build a model to predict a company’s bankruptcy, an analyst has collected a sample of data as follows:</p>
<p>Four financial ratios (predictors):</p>
<ul>
<li>x1: Retained Earnings / Total Assets<br />
</li>
<li>x2: Earnings Before Interest and Taxes / Total Assets<br />
</li>
<li>x3: Sales / Total Assets<br />
</li>
<li>x4: Cash Flow / Total Debt</li>
</ul>
<p>And a binary response variable y:</p>
<ul>
<li><p>0 - if the company went bankrupt</p></li>
<li><p>1 - if the company stayed solvent</p></li>
</ul>
</div>
<div id="importing-the-data-1" class="section level3 unnumbered hasAnchor">
<h3>Importing the data<a href="answers-2.html#importing-the-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="answers-2.html#cb248-1" tabindex="-1"></a>four_ratios <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/four_ratios.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="loading-required-packages-1" class="section level3 unnumbered hasAnchor">
<h3>Loading required packages<a href="answers-2.html#loading-required-packages-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="answers-2.html#cb249-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb249-2"><a href="answers-2.html#cb249-2" tabindex="-1"></a><span class="fu">library</span>(class)</span>
<span id="cb249-3"><a href="answers-2.html#cb249-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb249-4"><a href="answers-2.html#cb249-4" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb249-5"><a href="answers-2.html#cb249-5" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb249-6"><a href="answers-2.html#cb249-6" tabindex="-1"></a><span class="fu">library</span>(e1071)</span></code></pre></div>
<p>We can see that the predictors are all of class double. The response is of class integer, despite this being a binary categorical variable. There are a total of 111 observations, so quite a small dataset.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="answers-2.html#cb250-1" tabindex="-1"></a><span class="fu">glimpse</span>(four_ratios)</span></code></pre></div>
<pre><code>## Rows: 111
## Columns: 5
## $ x1 &lt;dbl&gt; 0.3778, 0.2783, 0.1192, 0.6070, 0.5334, 0.3868, 0.3312, 0.0130, 0.6…
## $ x2 &lt;dbl&gt; 0.1316, 0.1166, 0.2035, 0.2040, 0.1650, 0.0681, 0.2157, 0.2366, 0.2…
## $ x3 &lt;dbl&gt; 1.0911, 1.3441, 0.8130, 14.4090, 8.0734, 0.5755, 3.0679, 2.4709, 5.…
## $ x4 &lt;dbl&gt; 1.2784, 0.2216, 1.6702, 0.9844, 1.3474, 1.0579, 2.0899, 1.2230, 1.7…
## $ y  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…</code></pre>
<p>We therefore transform the response to a factor.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="answers-2.html#cb252-1" tabindex="-1"></a>four_ratios<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(four_ratios<span class="sc">$</span>y)</span></code></pre></div>
</div>
<div id="correlation-matrix-and-plot-2" class="section level3 unnumbered hasAnchor">
<h3>Correlation Matrix and Plot<a href="answers-2.html#correlation-matrix-and-plot-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now produce a correlation plot between all pairs of variables in the dataset.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="answers-2.html#cb253-1" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(four_ratios[,<span class="sc">-</span><span class="dv">5</span>])</span>
<span id="cb253-2"><a href="answers-2.html#cb253-2" tabindex="-1"></a></span>
<span id="cb253-3"><a href="answers-2.html#cb253-3" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">type =</span> <span class="st">&quot;lower&quot;</span>, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="03-S03-ANS_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>We observe a strong positive correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>. The correlations between other variables are quite weak.</p>
<p>Before we consider the model, we split the data into training and test sets as we will later on assess model accuracy in correct prediction using the test data set. We consider a basic fixed split of 80:20. Since there are a total of 111 observations, we split at row 89</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="answers-2.html#cb254-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb254-2"><a href="answers-2.html#cb254-2" tabindex="-1"></a>split_idx <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(four_ratios), <span class="dv">89</span>)</span>
<span id="cb254-3"><a href="answers-2.html#cb254-3" tabindex="-1"></a>train <span class="ot">=</span> four_ratios[split_idx, ]</span>
<span id="cb254-4"><a href="answers-2.html#cb254-4" tabindex="-1"></a>test <span class="ot">=</span> four_ratios[<span class="sc">-</span>split_idx, ]</span></code></pre></div>
</div>
<div id="logistic-regression-1" class="section level3 unnumbered hasAnchor">
<h3>Logistic Regression<a href="answers-2.html#logistic-regression-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now let’s first consider logistic regression and build the model. Given the high correlation between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> (this is to be expected, given what they measure), we have to reflect on how we want to address this. Assuming we have knowledge of important factors that can predict bankruptcy, we can decide to drop one of the two financial ratios. In this case, we drop <span class="math inline">\(x_2\)</span>.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="answers-2.html#cb255-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x3 <span class="sc">+</span> x4,</span>
<span id="cb255-2"><a href="answers-2.html#cb255-2" tabindex="-1"></a>           <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb255-3"><a href="answers-2.html#cb255-3" tabindex="-1"></a></span>
<span id="cb255-4"><a href="answers-2.html#cb255-4" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x1 + x3 + x4, family = binomial, data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1151  -0.4682   0.0000   0.3720   2.2542  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.6970     0.8896  -3.032  0.00243 ** 
## x1           12.6569     3.0942   4.090  4.3e-05 ***
## x3            1.6400     0.5764   2.845  0.00444 ** 
## x4           -0.5247     0.3297  -1.591  0.11151    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.369  on 88  degrees of freedom
## Residual deviance:  54.552  on 85  degrees of freedom
## AIC: 62.552
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>We now need to make a proper assessment to check if the variables collectively contribute in explaining the logit.</p>
<p>Therefore, we calculate the G statistic.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="answers-2.html#cb257-1" tabindex="-1"></a>G_calc <span class="ot">&lt;-</span> fit<span class="sc">$</span>null.deviance <span class="sc">-</span> fit<span class="sc">$</span>deviance</span>
<span id="cb257-2"><a href="answers-2.html#cb257-2" tabindex="-1"></a></span>
<span id="cb257-3"><a href="answers-2.html#cb257-3" tabindex="-1"></a>G_calc</span></code></pre></div>
<pre><code>## [1] 68.81702</code></pre>
<p>Then the degrees of freedom of the predictors.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="answers-2.html#cb259-1" tabindex="-1"></a>Gdf <span class="ot">&lt;-</span> fit<span class="sc">$</span>df.null <span class="sc">-</span> fit<span class="sc">$</span>df.residual</span>
<span id="cb259-2"><a href="answers-2.html#cb259-2" tabindex="-1"></a></span>
<span id="cb259-3"><a href="answers-2.html#cb259-3" tabindex="-1"></a>Gdf</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>We find the critical value for the G statistic.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="answers-2.html#cb261-1" tabindex="-1"></a><span class="fu">qchisq</span>(.<span class="dv">95</span>, <span class="at">df =</span> Gdf) </span></code></pre></div>
<pre><code>## [1] 7.814728</code></pre>
<p>And finally, the p-value associated with the G statistic.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="answers-2.html#cb263-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(G_calc, Gdf)</span></code></pre></div>
<pre><code>## [1] 7.660539e-15</code></pre>
<p>Now, we have to decide whether our model is a statistically valid one.
Since <span class="math inline">\(G_{calc} = 68.82 &gt; G_{crit} = 7.81 ⇒ H1,\)</span> (and the p-value is much smaller than 0.05), we can conclude that this is a statistically valid model and that the variables collectively have explanatory power.</p>
<p><strong>However, do we need ALL three variables?</strong></p>
<p>Rather than fitting individual models and doing a manual comparison we can make use of the anova function for comparing the nested model using the chi-square test.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="answers-2.html#cb265-1" tabindex="-1"></a><span class="fu">anova</span>(fit, <span class="at">test=</span><span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: y
## 
## Terms added sequentially (first to last)
## 
## 
##      Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                    88    123.369              
## x1    1   54.441        87     68.928 1.602e-13 ***
## x3    1   12.044        86     56.884 0.0005197 ***
## x4    1    2.332        85     54.552 0.1267323    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Based on the output, we can remove <span class="math inline">\(X_4\)</span> ratio variable from the model and we update our model (we also know that <span class="math inline">\(X_4\)</span> is not statistically significant from the summary of the model results earlier).</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="answers-2.html#cb267-1" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">update</span>(fit, <span class="sc">~</span>. <span class="sc">-</span>x4, <span class="at">data =</span> train)</span>
<span id="cb267-2"><a href="answers-2.html#cb267-2" tabindex="-1"></a></span>
<span id="cb267-3"><a href="answers-2.html#cb267-3" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x1 + x3, family = binomial, data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2116  -0.4985   0.0000   0.4300   2.3366  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -3.4779     0.8117  -4.285 1.83e-05 ***
## x1           11.6639     2.7793   4.197 2.71e-05 ***
## x3            1.6202     0.5754   2.816  0.00487 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.369  on 88  degrees of freedom
## Residual deviance:  56.884  on 86  degrees of freedom
## AIC: 62.884
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>To compare the fit of the new model we will use the Akaike Information Criterion (AIC), which is an index of fit that takes account of parsimony of the model by penalising for the number of parameters.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="answers-2.html#cb269-1" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x1 + x3, family = binomial, data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2116  -0.4985   0.0000   0.4300   2.3366  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -3.4779     0.8117  -4.285 1.83e-05 ***
## x1           11.6639     2.7793   4.197 2.71e-05 ***
## x3            1.6202     0.5754   2.816  0.00487 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.369  on 88  degrees of freedom
## Residual deviance:  56.884  on 86  degrees of freedom
## AIC: 62.884
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>The AIC of our initial model is 62.552 and of the new model 62.884 (very little difference). Checking the new model, we can see that it consists of the variables that all significantly contribute in explaining the logits. <em>So, in the spirit of parsimony we can choose the second model to be a better fit.</em> You will learn more about the AIC and other similar metrics later in the course.</p>
<p>To obtain the overall accuracy rate we need to find the predicted probabilities of the observations kept aside in the test subset.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="answers-2.html#cb271-1" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit2, test, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">&gt;</span> <span class="fl">0.5</span></span></code></pre></div>
<p>Now let’s compute the confusion matrix such that we can compare our predictions on the test data against the actual values in our dataset. We can see that our model predicts one instance incorrectly (it predicts <em>bankrupt</em> when in fact it should predict <em>solvent</em>)</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="answers-2.html#cb272-1" tabindex="-1"></a>(t <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">ifelse</span>(pred, <span class="st">&quot;Solvent (pred)&quot;</span>, <span class="st">&quot;Bankrupt (pred)&quot;</span>), test<span class="sc">$</span>y))</span></code></pre></div>
<pre><code>##                  
##                    0  1
##   Bankrupt (pred) 11  1
##   Solvent (pred)   0 10</code></pre>
<p>If we then compute the overall fraction of correct predictions, we can see that this is extremely high (0.955) which means that our model is performing extremely well. <em>In practice</em>: Although the overall accuracy rate might be easy to compute and to interpret, it makes no distinction about the type of errors being made. Although we did remove one the variables due to high correlation, other variables do show some degree of correlation and so we must be cautious about the strength of the relationship and therefore, the overall predictive performance.</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="answers-2.html#cb274-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(t)) <span class="sc">/</span> <span class="fu">sum</span>(t)</span></code></pre></div>
<pre><code>## [1] 0.9545455</code></pre>
<p><em>Do note that if you performing any rounding of the probabilities prior to classification, values near the threshold of 0.5 may be classified differently than if you were not to round the probabilities.</em></p>
</div>
<div id="linear-discriminant-analysis-1" class="section level3 unnumbered hasAnchor">
<h3>Linear Discriminant Analysis<a href="answers-2.html#linear-discriminant-analysis-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="task-1-12" class="section level4 unnumbered hasAnchor">
<h4>Task 1<a href="answers-2.html#task-1-12" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Build a LDA classifier for the final logistic model with two predictors and explain what the output means.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="answers-2.html#cb276-1" tabindex="-1"></a>fit_lda <span class="ot">&lt;-</span> <span class="fu">lda</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x3, <span class="at">data =</span> train)</span>
<span id="cb276-2"><a href="answers-2.html#cb276-2" tabindex="-1"></a></span>
<span id="cb276-3"><a href="answers-2.html#cb276-3" tabindex="-1"></a>fit_lda</span></code></pre></div>
<pre><code>## Call:
## lda(y ~ x1 + x3, data = train)
## 
## Prior probabilities of groups:
##        0        1 
## 0.494382 0.505618 
## 
## Group means:
##            x1        x3
## 0 0.009738636 0.4628477
## 1 0.341413333 2.6057978
## 
## Coefficients of linear discriminants:
##           LD1
## x1 4.61295546
## x3 0.06590811</code></pre>
<ul>
<li>prior probabilities of groups: these tells us the way in which the two classes are distributed in our <em>training data</em> (i.e. 49.4 % of the observations correspond to bankruptcy whilst 50.6 % to solvency).<br />
</li>
<li>group means: the average of the two predictors within each class which are used by LDA as an estimate of <span class="math inline">\(μ_{k}\)</span>.<br />
</li>
<li>coefficient(s) of linear discriminants: tells us how our predictor(s) influence the score that is used to classify the observations into one of the two categories. Here, the coefficients both predictors are positive and so this indicates that higher values for <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> will make the model more likely classify an observation as belonging to the <strong>solvent</strong> class; also, the larger the absolute value of the coefficient, the stronger the influence on the model.</li>
</ul>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="answers-2.html#cb278-1" tabindex="-1"></a>fit_lda</span></code></pre></div>
<pre><code>## Call:
## lda(y ~ x1 + x3, data = train)
## 
## Prior probabilities of groups:
##        0        1 
## 0.494382 0.505618 
## 
## Group means:
##            x1        x3
## 0 0.009738636 0.4628477
## 1 0.341413333 2.6057978
## 
## Coefficients of linear discriminants:
##           LD1
## x1 4.61295546
## x3 0.06590811</code></pre>
</div>
<div id="task-2-12" class="section level4 unnumbered hasAnchor">
<h4>Task 2<a href="answers-2.html#task-2-12" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Compute the predictions and explain what the results mean.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="answers-2.html#cb280-1" tabindex="-1"></a>result_lda <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_lda, test)</span></code></pre></div>
<p>The <code>class</code> component is a factor that contains the predictions for bankruptcy status (solvent/bankrupt).</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="answers-2.html#cb281-1" tabindex="-1"></a>result_lda<span class="sc">$</span>class</span></code></pre></div>
<pre><code>##  [1] 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0
## Levels: 0 1</code></pre>
<p>The <code>posterior</code> component is matrix that contains the posterior probability that the corresponding observation belongs to a given class.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="answers-2.html#cb283-1" tabindex="-1"></a>result_lda<span class="sc">$</span>posterior</span></code></pre></div>
<pre><code>##              0            1
## 1   0.17760365 8.223963e-01
## 2   0.31142722 6.885728e-01
## 10  0.07228194 9.277181e-01
## 11  0.33538335 6.646166e-01
## 19  0.04495309 9.550469e-01
## 20  0.17728895 8.227110e-01
## 24  0.40407718 5.959228e-01
## 28  0.22738932 7.726107e-01
## 29  0.14095907 8.590409e-01
## 37  0.53834405 4.616560e-01
## 40  0.70105814 2.989419e-01
## 44  0.85424906 1.457509e-01
## 45  0.73762416 2.623758e-01
## 49  0.95002382 4.997618e-02
## 56  0.99999946 5.413229e-07
## 58  0.83468414 1.653159e-01
## 62  0.87475890 1.252411e-01
## 64  0.94351212 5.648788e-02
## 66  0.25093559 7.490644e-01
## 85  0.61062622 3.893738e-01
## 105 0.99988023 1.197708e-04
## 109 0.96722224 3.277776e-02</code></pre>
<p>The <code>x</code> component contains the linear discriminants.</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="answers-2.html#cb285-1" tabindex="-1"></a>result_lda<span class="sc">$</span>x</span></code></pre></div>
<pre><code>##            LD1
## 1    0.8942494
## 2    0.4519351
## 10   1.5042674
## 11   0.3864033
## 19   1.8058326
## 20   0.8955396
## 24   0.2096297
## 28   0.7090237
## 29   1.0586059
## 37  -0.1147903
## 40  -0.5328419
## 44  -1.0809275
## 45  -0.6413331
## 49  -1.7849665
## 56  -8.6567024
## 58  -0.9916955
## 62  -1.1858701
## 64  -1.7075644
## 66   0.6315464
## 85  -0.2920645
## 105 -5.4259016
## 109 -2.0480872</code></pre>
<p>To obtain our predictions, we can simply extract the <code>class</code> element.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="answers-2.html#cb287-1" tabindex="-1"></a>pred_lda <span class="ot">&lt;-</span> result_lda<span class="sc">$</span>class</span></code></pre></div>
</div>
<div id="task-3-10" class="section level4 unnumbered hasAnchor">
<h4>Task 3<a href="answers-2.html#task-3-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Compute the confusion matrix for the LDA classifier and calculate the fraction of correct predictions. Explain the results.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="answers-2.html#cb288-1" tabindex="-1"></a>(t <span class="ot">&lt;-</span> <span class="fu">table</span>(pred_lda, test<span class="sc">$</span>y))</span></code></pre></div>
<pre><code>##         
## pred_lda  0  1
##        0 11  1
##        1  0 10</code></pre>
<p>And now the fraction of correct predictions which, we can see is identical to that obtained for logistic regression.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="answers-2.html#cb290-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(t)) <span class="sc">/</span> <span class="fu">sum</span>(t)</span></code></pre></div>
<pre><code>## [1] 0.9545455</code></pre>
<p>LDA performs identically to logistic regression.</p>
</div>
</div>
<div id="quadratic-discriminant-analysis-1" class="section level3 unnumbered hasAnchor">
<h3>Quadratic Discriminant Analysis<a href="answers-2.html#quadratic-discriminant-analysis-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="task-1-13" class="section level4 unnumbered hasAnchor">
<h4>Task 1<a href="answers-2.html#task-1-13" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Build a QDA clasifier and describe the output.</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="answers-2.html#cb292-1" tabindex="-1"></a>fit_qda <span class="ot">&lt;-</span> <span class="fu">qda</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x3, <span class="at">data =</span> train)</span>
<span id="cb292-2"><a href="answers-2.html#cb292-2" tabindex="-1"></a></span>
<span id="cb292-3"><a href="answers-2.html#cb292-3" tabindex="-1"></a>fit_qda</span></code></pre></div>
<pre><code>## Call:
## qda(y ~ x1 + x3, data = train)
## 
## Prior probabilities of groups:
##        0        1 
## 0.494382 0.505618 
## 
## Group means:
##            x1        x3
## 0 0.009738636 0.4628477
## 1 0.341413333 2.6057978</code></pre>
<p>In terms of prior probabilities and group means, the output is identical to that of linear discriminant analysis. However, the output does not include the coefficients of the <em>linear</em> discriminants for obvious reasons.</p>
</div>
<div id="task-2-13" class="section level4 unnumbered hasAnchor">
<h4>Task 2<a href="answers-2.html#task-2-13" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Compute the predictions, the confusion matrix, and the fraction of correct predictions and explain what the results mean.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="answers-2.html#cb294-1" tabindex="-1"></a>pred_qda <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_qda, test, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)<span class="sc">$</span>class</span>
<span id="cb294-2"><a href="answers-2.html#cb294-2" tabindex="-1"></a></span>
<span id="cb294-3"><a href="answers-2.html#cb294-3" tabindex="-1"></a>(t <span class="ot">&lt;-</span> <span class="fu">table</span>(pred_qda, test<span class="sc">$</span>y))</span></code></pre></div>
<pre><code>##         
## pred_qda  0  1
##        0 11  6
##        1  0  5</code></pre>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="answers-2.html#cb296-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(t)) <span class="sc">/</span> <span class="fu">sum</span>(t)</span></code></pre></div>
<pre><code>## [1] 0.7272727</code></pre>
<p>The fraction of correct predictions is lower (0.73) than that for logistic regression and for LDA (0.95). We therefore conclude that in this context, QDA does not perform well in comparison to the previous two approaches.</p>
</div>
</div>
<div id="k-nearest-neighbours-1" class="section level3 unnumbered hasAnchor">
<h3><span class="math inline">\(K\)</span>-nearest neighbours<a href="answers-2.html#k-nearest-neighbours-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="task-1-14" class="section level4 unnumbered hasAnchor">
<h4>Task 1<a href="answers-2.html#task-1-14" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Perform KNN regression on the same model as in the previous tasks.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="answers-2.html#cb298-1" tabindex="-1"></a>fit_knn <span class="ot">&lt;-</span> <span class="fu">knn</span>(train[, <span class="fu">c</span>(<span class="st">&quot;x1&quot;</span>, <span class="st">&quot;x3&quot;</span>), <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb298-2"><a href="answers-2.html#cb298-2" tabindex="-1"></a>               test[, <span class="fu">c</span>(<span class="st">&quot;x1&quot;</span>, <span class="st">&quot;x3&quot;</span>), <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb298-3"><a href="answers-2.html#cb298-3" tabindex="-1"></a>               train<span class="sc">$</span>y, </span>
<span id="cb298-4"><a href="answers-2.html#cb298-4" tabindex="-1"></a>               <span class="at">k =</span> <span class="dv">1</span></span>
<span id="cb298-5"><a href="answers-2.html#cb298-5" tabindex="-1"></a>               )</span></code></pre></div>
</div>
<div id="task-2-14" class="section level4 unnumbered hasAnchor">
<h4>Task 2<a href="answers-2.html#task-2-14" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Produce a confusion matrix and compute the fraction of correct predictions. Comment on the results.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="answers-2.html#cb299-1" tabindex="-1"></a>(t <span class="ot">&lt;-</span> <span class="fu">table</span>(fit_knn, test<span class="sc">$</span>y))</span></code></pre></div>
<pre><code>##        
## fit_knn  0  1
##       0 10  1
##       1  1 10</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="answers-2.html#cb301-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(t)) <span class="sc">/</span> <span class="fu">sum</span>(t)</span></code></pre></div>
<pre><code>## [1] 0.9090909</code></pre>
<p>Our overall fraction of correct predictions is 0.91. Therefore, the KNN classifier (<span class="math inline">\(k = 1\)</span>) performs better than QDA (0.73), but worse than logistic regression and and LDA (0.95).</p>
</div>
<div id="task-3-11" class="section level4 unnumbered hasAnchor">
<h4>Task 3<a href="answers-2.html#task-3-11" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Fit KNN for up to <span class="math inline">\(k = 30\)</span> and then calculate the overall fraction of correct prediction.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="answers-2.html#cb303-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb303-2"><a href="answers-2.html#cb303-2" tabindex="-1"></a>knn_k <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>, <span class="cf">function</span>(k) {</span>
<span id="cb303-3"><a href="answers-2.html#cb303-3" tabindex="-1"></a>  fit_knn <span class="ot">&lt;-</span> <span class="fu">knn</span>(train[, <span class="fu">c</span>(<span class="st">&quot;x1&quot;</span>, <span class="st">&quot;x3&quot;</span>), <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb303-4"><a href="answers-2.html#cb303-4" tabindex="-1"></a>                 test[, <span class="fu">c</span>(<span class="st">&quot;x1&quot;</span>, <span class="st">&quot;x3&quot;</span>), <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb303-5"><a href="answers-2.html#cb303-5" tabindex="-1"></a>                 train<span class="sc">$</span>y, <span class="at">k =</span> k)</span>
<span id="cb303-6"><a href="answers-2.html#cb303-6" tabindex="-1"></a>  <span class="fu">mean</span>(fit_knn <span class="sc">==</span> test<span class="sc">$</span>y)</span>
<span id="cb303-7"><a href="answers-2.html#cb303-7" tabindex="-1"></a>})</span></code></pre></div>
</div>
<div id="task-4-9" class="section level4 unnumbered hasAnchor">
<h4>Task 4<a href="answers-2.html#task-4-9" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Create a plot to observe at what value for <code>k</code> the overall fraction of correct predictions is highest.</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="answers-2.html#cb304-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>, knn_k, <span class="at">type =</span> <span class="st">&quot;o&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;k&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Fraction correct&quot;</span>)</span></code></pre></div>
<p><img src="03-S03-ANS_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>As you can see, the highest fraction of correct predictions is when <span class="math inline">\(k = 1\)</span> (also confirmed by using <code>which.max</code>).</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="answers-2.html#cb305-1" tabindex="-1"></a>(k <span class="ot">&lt;-</span> <span class="fu">which.max</span>(knn_k))</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>The behaviour you observe results from several reasons, one of which is the size of the dataset.</p>
</div>
</div>
<div id="naive-bayes-1" class="section level3 unnumbered hasAnchor">
<h3>Naive Bayes<a href="answers-2.html#naive-bayes-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="task-1-15" class="section level4 unnumbered hasAnchor">
<h4>Task 1<a href="answers-2.html#task-1-15" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Build a Naive Bayes classifier for the model used previously and describe the output.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="answers-2.html#cb307-1" tabindex="-1"></a>fit_NBayes <span class="ot">&lt;-</span> <span class="fu">naiveBayes</span>(y<span class="sc">~</span> x1 <span class="sc">+</span> x3, <span class="at">data =</span> train)</span>
<span id="cb307-2"><a href="answers-2.html#cb307-2" tabindex="-1"></a></span>
<span id="cb307-3"><a href="answers-2.html#cb307-3" tabindex="-1"></a>fit_NBayes</span></code></pre></div>
<pre><code>## 
## Naive Bayes Classifier for Discrete Predictors
## 
## Call:
## naiveBayes.default(x = X, y = Y, laplace = laplace)
## 
## A-priori probabilities:
## Y
##        0        1 
## 0.494382 0.505618 
## 
## Conditional probabilities:
##    x1
## Y          [,1]      [,2]
##   0 0.009738636 0.2458544
##   1 0.341413333 0.1529747
## 
##    x3
## Y        [,1]      [,2]
##   0 0.4628477 0.5992219
##   1 2.6057978 5.0402790</code></pre>
<ul>
<li>A-priori probabilities: i.e. prior probabilities (distribution of the classes for the response variable)<br />
</li>
<li>Conditional probabilities: parameters of the model for each predictor by class. Since the predictors are numeric variables, the parameters shown are the mean <code>[,1]</code> and standard deviation <code>[,2]</code> for the predictor values in each class.</li>
</ul>
</div>
<div id="task-2-15" class="section level4 unnumbered hasAnchor">
<h4>Task 2<a href="answers-2.html#task-2-15" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Compute the predictions, build a confusion matrix, calculate the fraction of correct predictions and interpret the results.</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="answers-2.html#cb309-1" tabindex="-1"></a>pred_NBayes <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_NBayes, test, <span class="at">type =</span> <span class="st">&quot;class&quot;</span>)</span></code></pre></div>
<p>And finally, generate our confusion matrix.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="answers-2.html#cb310-1" tabindex="-1"></a>(t <span class="ot">&lt;-</span> <span class="fu">table</span>(pred_NBayes, test<span class="sc">$</span>y))</span></code></pre></div>
<pre><code>##            
## pred_NBayes  0  1
##           0 11  8
##           1  0  3</code></pre>
<p>Our overall fraction of correct predictions is <span class="math inline">\(0.64\)</span>.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="answers-2.html#cb312-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(t)) <span class="sc">/</span> <span class="fu">sum</span>(t)</span></code></pre></div>
<pre><code>## [1] 0.6363636</code></pre>
<p>Naive Bayes performs the worst out of all classifiers we have explored.</p>
<p><em>Based on the approaches we have implemented in this demonstration, logistic regression and LDA perform best.</em></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="practical-predicting-a-companys-bankruptcy.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
