<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Demonstration | R Notebook</title>
  <meta name="description" content="Notebook hosting practical materials for SOST70033." />
  <meta name="generator" content="bookdown 0.38 and GitBook 2.6.7" />

  <meta property="og:title" content="Demonstration | R Notebook" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notebook hosting practical materials for SOST70033." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Demonstration | R Notebook" />
  
  <meta name="twitter:description" content="Notebook hosting practical materials for SOST70033." />
  

<meta name="author" content="Dr. Ioana Macoveciuc" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="overview-7.html"/>
<link rel="next" href="your-turn.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/logos/uom_logo.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="part"><span><b>Section 1</b></span></li>
<li class="chapter" data-level="" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-a-more-in-depth-consideration-of-model-accuracy.html"><a href="demonstration-a-more-in-depth-consideration-of-model-accuracy.html"><i class="fa fa-check"></i>Demonstration: A more in-depth consideration of model accuracy</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-a-more-in-depth-consideration-of-model-accuracy.html"><a href="demonstration-a-more-in-depth-consideration-of-model-accuracy.html#the-simulation"><i class="fa fa-check"></i>The Simulation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-1"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-2"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-3"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-4"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-5"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-6"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-7"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-8"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-9"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-10"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="practical-1.html"><a href="practical-1.html#task-11"><i class="fa fa-check"></i>Task 11</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-1-1"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-2-1"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-3-1"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-4-1"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-5-1"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="practical-2.html"><a href="practical-2.html#task-6-1"><i class="fa fa-check"></i>Task 6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html"><i class="fa fa-check"></i>Answers</a>
<ul>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#practical-1-1"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-1-2"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-2-2"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-3-2"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-4-2"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-5-2"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-6-2"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-7-1"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-8-1"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-9-1"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-10-1"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-11-1"><i class="fa fa-check"></i>Task 11</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#practical-2-1"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-1-3"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-2-3"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-3-3"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-4-3"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-5-3"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html#task-6-3"><i class="fa fa-check"></i>Task 6</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Section 2</b></span></li>
<li class="chapter" data-level="" data-path="overview-1.html"><a href="overview-1.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-1.html"><a href="demonstration-1.html"><i class="fa fa-check"></i>Demonstration 1</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1.html"><a href="demonstration-1.html#simple-linear-models-without-intercept"><i class="fa fa-check"></i>Simple Linear Models Without Intercept</a></li>
<li class="chapter" data-level="" data-path="demonstration-1.html"><a href="demonstration-1.html#simple-linear-models-with-intercept"><i class="fa fa-check"></i>Simple Linear Models with Intercept</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html"><i class="fa fa-check"></i>Demonstration 2</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#population-parameters-and-estimated-coefficients"><i class="fa fa-check"></i>Population Parameters and Estimated Coefficients</a></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#what-happens-if-we-reduce-noise"><i class="fa fa-check"></i>What happens if we <em>reduce</em> noise?</a></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#what-happens-if-we-increase-noise"><i class="fa fa-check"></i>What happens if we <em>increase</em> noise?</a></li>
<li class="chapter" data-level="" data-path="demonstration-2.html"><a href="demonstration-2.html#how-does-noise-affect-confidence-intervals-for-the-coefficients"><i class="fa fa-check"></i>How does noise affect confidence intervals for the coefficients?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-1-4"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-2-4"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-3-4"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-4-4"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-5-4"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-6-4"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-7-2"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-8-2"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-9-2"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-10-2"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-11-2"><i class="fa fa-check"></i>Task 11</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-12"><i class="fa fa-check"></i>Task 12</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-13"><i class="fa fa-check"></i>Task 13</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-14"><i class="fa fa-check"></i>Task 14</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-15"><i class="fa fa-check"></i>Task 15</a></li>
<li class="chapter" data-level="" data-path="practical-1-2.html"><a href="practical-1-2.html#task-16"><i class="fa fa-check"></i>Task 16</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-1-5"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-2-5"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-3-5"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-4-5"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="practical-2-2.html"><a href="practical-2-2.html#task-5-5"><i class="fa fa-check"></i>Task 5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html"><i class="fa fa-check"></i>Answers</a>
<ul>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#practical-1-3"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-1-6"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-2-6"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-3-6"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-4-6"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-5-6"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-6-5"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-7-3"><i class="fa fa-check"></i>Task 7</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-8-3"><i class="fa fa-check"></i>Task 8</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-9-3"><i class="fa fa-check"></i>Task 9</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-10-3"><i class="fa fa-check"></i>Task 10</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-11-3"><i class="fa fa-check"></i>Task 11</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-12-1"><i class="fa fa-check"></i>Task 12</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-13-1"><i class="fa fa-check"></i>Task 13</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-14-1"><i class="fa fa-check"></i>Task 14</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-15-1"><i class="fa fa-check"></i>Task 15</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-16-1"><i class="fa fa-check"></i>Task 16</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#practical-2-3"><i class="fa fa-check"></i>Practical 2</a>
<ul>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-1-7"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-2-7"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-3-7"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-4-7"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="answers-1.html"><a href="answers-1.html#task-5-7"><i class="fa fa-check"></i>Task 5</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Section 3</b></span></li>
<li class="chapter" data-level="" data-path="overview-2.html"><a href="overview-2.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html"><i class="fa fa-check"></i>Demonstration: Classification Problems</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#dataset-and-variables"><i class="fa fa-check"></i>Dataset and Variables</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#correlation-matrix-and-plot"><i class="fa fa-check"></i>Correlation Matrix and Plot</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#classic-logistic-regression"><i class="fa fa-check"></i>“Classic” Logistic Regression</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#confusion-matrix"><i class="fa fa-check"></i>Confusion Matrix</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#logistic-regression-in-statistical-learning"><i class="fa fa-check"></i>Logistic Regression in Statistical Learning</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#linear-discriminant-analysis"><i class="fa fa-check"></i>Linear Discriminant Analysis</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#quadratic-discriminant-analysis"><i class="fa fa-check"></i>Quadratic Discriminant Analysis</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#k-nearest-neighbours"><i class="fa fa-check"></i><span class="math inline">\(K\)</span>-nearest neighbours</a></li>
<li class="chapter" data-level="" data-path="demonstration-classification-problems.html"><a href="demonstration-classification-problems.html#naive-bayes"><i class="fa fa-check"></i>Naive Bayes</a></li>
</ul></li>
<li class="part"><span><b>Section 4</b></span></li>
<li class="chapter" data-level="" data-path="overview-3.html"><a href="overview-3.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-cross-validation.html"><a href="demonstration-1-cross-validation.html"><i class="fa fa-check"></i>Demonstration 1: Cross-validation</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1-cross-validation.html"><a href="demonstration-1-cross-validation.html#data-and-variables"><i class="fa fa-check"></i>Data and Variables</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-cross-validation.html"><a href="demonstration-1-cross-validation.html#the-validation-set-approach"><i class="fa fa-check"></i>The Validation Set Approach</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-cross-validation.html"><a href="demonstration-1-cross-validation.html#leave-one-out-cross-validation"><i class="fa fa-check"></i>Leave-One-Out Cross-Validation</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-cross-validation.html"><a href="demonstration-1-cross-validation.html#k-fold-cross-validation"><i class="fa fa-check"></i><span class="math inline">\(k\)</span>-Fold Cross-Validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-2-bootstrapping.html"><a href="demonstration-2-bootstrapping.html"><i class="fa fa-check"></i>Demonstration 2: Bootstrapping</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-2-bootstrapping.html"><a href="demonstration-2-bootstrapping.html#data-and-variables-1"><i class="fa fa-check"></i>Data and Variables</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-bootstrapping.html"><a href="demonstration-2-bootstrapping.html#estimating-the-accuracy-of-a-statistic-of-interest"><i class="fa fa-check"></i>Estimating the Accuracy of a Statistic of Interest</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-bootstrapping.html"><a href="demonstration-2-bootstrapping.html#estimating-the-accuracy-of-a-linear-regression-model"><i class="fa fa-check"></i>Estimating the Accuracy of a Linear Regression Model</a></li>
</ul></li>
<li class="part"><span><b>Section 5</b></span></li>
<li class="chapter" data-level="" data-path="overview-4.html"><a href="overview-4.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="0.1" data-path="overview-4.html"><a href="overview-4.html#learning-outcomes"><i class="fa fa-check"></i><b>0.1</b> <strong>Learning Outcomes:</strong></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html"><i class="fa fa-check"></i>Practical 1: Academic Salary</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#part-i"><i class="fa fa-check"></i>Part I</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#exploring-the-data"><i class="fa fa-check"></i>Exploring the data</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#salary-and-years-since-phd"><i class="fa fa-check"></i>Salary and Years since PhD</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#salary-and-years-of-service"><i class="fa fa-check"></i>Salary and Years of Service</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#the-model"><i class="fa fa-check"></i>The Model</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#test-a-does-the-fitted-model-make-sense"><i class="fa fa-check"></i>Test a): Does the fitted model make sense?</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#test-b-overall-is-the-model-a-good-fit"><i class="fa fa-check"></i>Test b): Overall, is the model a good fit?</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#test-c-individually-are-the-explanatory-variables-important"><i class="fa fa-check"></i>Test c): Individually, are the explanatory variables important?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#part-ii"><i class="fa fa-check"></i>Part II</a>
<ul>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#interpreting-coefficients-of-attribute-variables"><i class="fa fa-check"></i>Interpreting coefficients of attribute variables</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#fitting-a-multivariate-regression-model"><i class="fa fa-check"></i>Fitting a Multivariate Regression Model</a></li>
<li class="chapter" data-level="" data-path="practical-1-academic-salary.html"><a href="practical-1-academic-salary.html#fitting-the-model"><i class="fa fa-check"></i>Fitting the Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="practical-2-foreign-direct-investment-fdi-study.html"><a href="practical-2-foreign-direct-investment-fdi-study.html"><i class="fa fa-check"></i>Practical 2: Foreign Direct Investment (FDI) Study</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html"><i class="fa fa-check"></i>Demonstration: ProPublica’s Analysis of the COMPAS Tool</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#notes-on-the-data"><i class="fa fa-check"></i>Notes on the data</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#setup"><i class="fa fa-check"></i>Setup</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#load-packages"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#load-data"><i class="fa fa-check"></i>Load data</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#inspect-data"><i class="fa fa-check"></i>Inspect data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#preprocess-data"><i class="fa fa-check"></i>Preprocess data</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#inspect-data-again"><i class="fa fa-check"></i>Inspect data again</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#exploratory-analysis"><i class="fa fa-check"></i>Exploratory analysis</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#exercise"><i class="fa fa-check"></i>👉 Exercise</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#risk-labels"><i class="fa fa-check"></i>Risk labels</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#bias-in-compas"><i class="fa fa-check"></i>Bias in COMPAS</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#preprocess-data-for-logistic-regression"><i class="fa fa-check"></i>Preprocess data for logistic regression</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#estimate-the-logistic-regression-model"><i class="fa fa-check"></i>Estimate the logistic regression model</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#interpret-estimates"><i class="fa fa-check"></i>Interpret estimates</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#exercise-1"><i class="fa fa-check"></i>👉 Exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#predictive-accuracy"><i class="fa fa-check"></i>Predictive Accuracy</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#exercise-2"><i class="fa fa-check"></i>👉 Exercise</a></li>
<li class="chapter" data-level="" data-path="demonstration-propublicas-analysis-of-the-compas-tool.html"><a href="demonstration-propublicas-analysis-of-the-compas-tool.html#exercise-3"><i class="fa fa-check"></i>👉 Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html"><i class="fa fa-check"></i>Answers</a>
<ul>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#practical-1-4"><i class="fa fa-check"></i>Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#part-i-1"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#part-ii-1"><i class="fa fa-check"></i>Part II</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers-2.html"><a href="answers-2.html#practical-2-4"><i class="fa fa-check"></i>Practical 2</a></li>
</ul></li>
<li class="part"><span><b>Section 6</b></span></li>
<li class="chapter" data-level="" data-path="overview-5.html"><a href="overview-5.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="practical.html"><a href="practical.html"><i class="fa fa-check"></i>Practical</a></li>
<li class="part"><span><b>Section 7</b></span></li>
<li class="chapter" data-level="" data-path="overview-6.html"><a href="overview-6.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html"><i class="fa fa-check"></i>Demonstration 1: K-means Clustering in R</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#loading-the-necessary-packages"><i class="fa fa-check"></i>Loading the necessary packages</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#profile-the-palmer-penguins-dataset"><i class="fa fa-check"></i>Profile the Palmer Penguins dataset</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#plot"><i class="fa fa-check"></i>Plot</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#preprocess-the-data-for-clustering"><i class="fa fa-check"></i>Preprocess the data for clustering</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#perform-k-means-clustering"><i class="fa fa-check"></i>Perform k-means clustering</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#visualise-the-clusters"><i class="fa fa-check"></i>Visualise the clusters</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#tasks"><i class="fa fa-check"></i>👉 TASKS</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#task-1-how-well-did-k-means-clustering-perform"><i class="fa fa-check"></i>TASK 1: How well did k-means clustering perform?</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#task-2-how-many-clusters-should-we-use"><i class="fa fa-check"></i>TASK 2: How many clusters should we use?</a></li>
<li class="chapter" data-level="" data-path="demonstration-1-k-means-clustering-in-r.html"><a href="demonstration-1-k-means-clustering-in-r.html#task-3-clustering-cars"><i class="fa fa-check"></i>TASK 3: Clustering cars</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html"><i class="fa fa-check"></i>Demonstration 2: Principal Component Analysis in R</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#load-packages-1"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#preprocess-the-world-happiness-report-data"><i class="fa fa-check"></i>Preprocess the world happiness report data</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#profile-the-happiness-data"><i class="fa fa-check"></i>Profile the happiness data</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#plot-happiness-score-against-feature"><i class="fa fa-check"></i>Plot happiness score against feature</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#run-pca-using-five-features"><i class="fa fa-check"></i>Run PCA using five features</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#correlations-of-happiness-score-with-pc1-and-pc2"><i class="fa fa-check"></i>Correlations of happiness score with PC1 and PC2</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#plot-first-two-principal-components"><i class="fa fa-check"></i>Plot first two principal components</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#regress-happiness-on-the-five-indicators"><i class="fa fa-check"></i>Regress happiness on the five indicators</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#visualise-happiness-against-principal-components"><i class="fa fa-check"></i>Visualise happiness against principal components</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#regress-happiness-on-first-principal-component"><i class="fa fa-check"></i>Regress happiness on first principal component</a></li>
<li class="chapter" data-level="" data-path="demonstration-2-principal-component-analysis-in-r.html"><a href="demonstration-2-principal-component-analysis-in-r.html#task"><i class="fa fa-check"></i>👉 TASK</a></li>
</ul></li>
<li class="part"><span><b>Section 8</b></span></li>
<li class="chapter" data-level="" data-path="overview-7.html"><a href="overview-7.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html"><i class="fa fa-check"></i>Demonstration</a>
<ul>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#data-set"><i class="fa fa-check"></i>Data Set</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#project-planning-setting-the-stage-for-success"><i class="fa fa-check"></i>Project Planning: Setting the Stage for Success</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#data-preprocessing"><i class="fa fa-check"></i>Data Preprocessing</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#exploratory-data-analysis-eda"><i class="fa fa-check"></i>Exploratory Data Analysis (EDA)</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#model-selection-and-model-training"><i class="fa fa-check"></i>Model Selection and Model Training</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#model-evaluation"><i class="fa fa-check"></i>Model Evaluation</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#model-interpretation"><i class="fa fa-check"></i>Model Interpretation</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#report-conclusion"><i class="fa fa-check"></i>Report Conclusion</a></li>
<li class="chapter" data-level="" data-path="demonstration.html"><a href="demonstration.html#key-insights"><i class="fa fa-check"></i>Key Insights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="your-turn.html"><a href="your-turn.html"><i class="fa fa-check"></i>👉 Your Turn!</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Notebook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<hr>
<center> 
  <div class="header">
   <img src="images/banners/DSM_banner.png" alt="Trulli">
  </div>
</center>
<div id="demonstration" class="section level1 unnumbered hasAnchor">
<h1>Demonstration<a href="demonstration.html#demonstration" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>Enhancing Data Science Projects with ChatGPT: A Case Study in R.</em></p>
<div id="data-set" class="section level2 unnumbered hasAnchor">
<h2>Data Set<a href="demonstration.html#data-set" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Spanish Wine Quality Dataset focuses on red wine variants from Spain, detailing various metrics related to their popularity and characteristics, and their influence on quality. It is suitable for classification or regression tasks, with the goal being to predict the quality or price of the wines. Note that the quality ratings range from nearly 5 to 4 points and are not evenly distributed. The dataset comprises 7,500 different types of Spanish red wines, each described by 11 features including price, rating, and flavor descriptors. The data was meticulously gathered through web scraping from diverse sources, such as specialised wine websites and supermarkets.</p>
<p>Attribute Information</p>
<ul>
<li>winery: Name of the winery</li>
<li>wine: Name of the wine</li>
<li>year: Harvest year of the grapes</li>
<li>rating: Average user rating (1-5)</li>
<li>num_reviews: Number of user reviews</li>
<li>country: Country of origin (Spain)</li>
<li>region: Wine-producing region</li>
<li>price: Price in euros (€)</li>
<li>type: Wine variety</li>
<li>body: Body score, indicating the richness and weight of the wine (1-5)</li>
<li>acidity: Acidity score, indicating the wine’s tartness and refreshing quality (1-5)</li>
</ul>
<p>To start our AI-aided data science project, we’ll need to download the dataset named <code>wines_SPA.csv</code>. Save this dataset in a “data” folder within a new project directory called <code>wines_SPA</code>.</p>
<p><img src="images/data_folder.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Before we begin, let’s take an initial look at the dataset. Open the downloaded csv file to ensure it’s functional and contains the data we need.</p>
<p><img src="images/wines_SPA_csv.png" width="85%" style="display: block; margin: auto;" /></p>
<p>After that, we’ll set up an R project file and dive into our data science project.</p>
<p><img src="images/Rproj.png" width="85%" style="display: block; margin: auto;" /></p>
<p><em>Exciting times ahead!</em></p>
</div>
<div id="project-planning-setting-the-stage-for-success" class="section level2 unnumbered hasAnchor">
<h2>Project Planning: Setting the Stage for Success<a href="demonstration.html#project-planning-setting-the-stage-for-success" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Project planning is a critical phase where we assess available resources and goals to develop an optimal strategy. To initiate this process, visit <a href="chat.openai.com">chatGPT</a> and start a new chat. Mention the availability of the Spanish Wine Quality dataset and ask ChatGPT to provide steps for building an end-to-end generic portfolio project. This step lays the groundwork for a successful project by defining clear objectives and identifying the necessary resources.</p>
<p><span style="color:red"><strong>Prompt:</strong> </span> <span style="color:gray"> <em>I have The Spanish Wine Quality Dataset, which centers on red wine variations from Spain. It provides detailed metrics regarding their popularity, characteristics, and how these factors influence quality. This dataset is ideal for classification or regression tasks, aiming to predict the quality or price of wines. It’s worth noting that the quality ratings range from nearly 5 to 4 points and are not evenly distributed. The dataset includes 7,500 different types of Spanish red wines, each described by 11 features such as price, rating, and flavor descriptors. Could you guide me through the necessary steps for this data science project using this dataset</em></span></p>
<p><span style="color:red"><strong>ChatGPT</strong></span>
<img src="images/prompt1.gif" width="85%" style="display: block; margin: auto;" /></p>
<p>To be in line with our adopted practice, we will summarise ChatGPT’s suggestions into the following set of steps:</p>
<ol style="list-style-type: lower-roman">
<li>Data Preprocessing + Feature Engineering<br />
</li>
<li>Exploratory Data Analysis (EDA) + Feature Engineering if still needed<br />
</li>
<li>Model Selection and Model Training<br />
</li>
<li>Model Evaluation<br />
</li>
<li>Model Interpretation<br />
</li>
<li>Conclusion</li>
</ol>
</div>
<div id="data-preprocessing" class="section level2 unnumbered hasAnchor">
<h2>Data Preprocessing<a href="demonstration.html#data-preprocessing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we use ChatGPT to assist us in this project, some steps will be performed without its aid. These include loading the necessary packages, uploading data, and converting some character-type variables into appropriate factor types.</p>
<p>❗️<span style="color:green"> Please ensure that you have installed all necessary packages before proceeding with these steps. </span></p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="demonstration.html#cb463-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Load packages</span></span>
<span id="cb463-2"><a href="demonstration.html#cb463-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Note that you will need to install some of these packages</span></span>
<span id="cb463-3"><a href="demonstration.html#cb463-3" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb463-4"><a href="demonstration.html#cb463-4" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">library</span>(ggplot2) <span class="co"># For creating visualisations.</span></span>
<span id="cb463-5"><a href="demonstration.html#cb463-5" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(dplyr) <span class="co"># For wrangling data.</span></span>
<span id="cb463-6"><a href="demonstration.html#cb463-6" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(tidyr) <span class="co"># For data tidying operations.</span></span>
<span id="cb463-7"><a href="demonstration.html#cb463-7" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(reshape2) <span class="co"># For reshaping data frames.</span></span>
<span id="cb463-8"><a href="demonstration.html#cb463-8" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(caret) <span class="co"># For data preprocessing tasks like scaling and imputing missing values and ML.</span></span>
<span id="cb463-9"><a href="demonstration.html#cb463-9" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(glmnet) <span class="co"># For fitting Lasso and Ridge regression models.</span></span>
<span id="cb463-10"><a href="demonstration.html#cb463-10" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(randomForest) <span class="co"># For fitting Random Forest models.</span></span>
<span id="cb463-11"><a href="demonstration.html#cb463-11" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(rpart) <span class="co"># For fitting and visualising decision trees.</span></span>
<span id="cb463-12"><a href="demonstration.html#cb463-12" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(rpart.plot) <span class="co"># For visualising decision trees created with the `rpart` package.</span></span>
<span id="cb463-13"><a href="demonstration.html#cb463-13" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(splines) <span class="co"># For creating spline basis functions for use in generalised linear models (GLMs)</span></span>
<span id="cb463-14"><a href="demonstration.html#cb463-14" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb463-15"><a href="demonstration.html#cb463-15" tabindex="-1"></a><span class="er">&gt;</span> <span class="co">#read data</span></span>
<span id="cb463-16"><a href="demonstration.html#cb463-16" tabindex="-1"></a><span class="er">&gt;</span> wine_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/wines_SPA.csv&#39;</span>,</span>
<span id="cb463-17"><a href="demonstration.html#cb463-17" tabindex="-1"></a><span class="sc">+</span>                     <span class="at">header=</span><span class="cn">TRUE</span>, </span>
<span id="cb463-18"><a href="demonstration.html#cb463-18" tabindex="-1"></a><span class="sc">+</span>                     <span class="at">na.strings=</span><span class="fu">c</span>(<span class="st">&quot;&quot;</span>,<span class="st">&quot;NA&quot;</span>),</span>
<span id="cb463-19"><a href="demonstration.html#cb463-19" tabindex="-1"></a><span class="sc">+</span>                     <span class="at">stringsAsFactor =</span> <span class="cn">FALSE</span>) </span>
<span id="cb463-20"><a href="demonstration.html#cb463-20" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">glimpse</span>(wine_data)</span></code></pre></div>
<pre><code>## Rows: 7,500
## Columns: 11
## $ winery      &lt;chr&gt; &quot;Teso La Monja&quot;, &quot;Artadi&quot;, &quot;Vega Sicilia&quot;, &quot;Vega Sicilia&quot;,…
## $ wine        &lt;chr&gt; &quot;Tinto&quot;, &quot;Vina El Pison&quot;, &quot;Unico&quot;, &quot;Unico&quot;, &quot;Unico&quot;, &quot;Unic…
## $ year        &lt;chr&gt; &quot;2013&quot;, &quot;2018&quot;, &quot;2009&quot;, &quot;1999&quot;, &quot;1996&quot;, &quot;1998&quot;, &quot;2010&quot;, &quot;1…
## $ rating      &lt;dbl&gt; 4.9, 4.9, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8…
## $ num_reviews &lt;int&gt; 58, 31, 1793, 1705, 1309, 1209, 1201, 926, 643, 630, 591, …
## $ country     &lt;chr&gt; &quot;Espana&quot;, &quot;Espana&quot;, &quot;Espana&quot;, &quot;Espana&quot;, &quot;Espana&quot;, &quot;Espana&quot;…
## $ region      &lt;chr&gt; &quot;Toro&quot;, &quot;Vino de Espana&quot;, &quot;Ribera del Duero&quot;, &quot;Ribera del …
## $ price       &lt;dbl&gt; 995.0000, 313.5000, 324.9500, 692.9600, 778.0600, 490.0000…
## $ type        &lt;chr&gt; &quot;Toro Red&quot;, &quot;Tempranillo&quot;, &quot;Ribera Del Duero Red&quot;, &quot;Ribera…
## $ body        &lt;int&gt; 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5…
## $ acidity     &lt;int&gt; 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3…</code></pre>
<p>Next, we will convert character types into factors and change the <code>year</code> variable to an integer type. We will also remove the <code>country</code> variable since all the wine is from Spain.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="demonstration.html#cb465-1" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wine_data[,<span class="dv">1</span>])</span>
<span id="cb465-2"><a href="demonstration.html#cb465-2" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wine_data[,<span class="dv">2</span>])</span>
<span id="cb465-3"><a href="demonstration.html#cb465-3" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(wine_data[,<span class="dv">3</span>])</span>
<span id="cb465-4"><a href="demonstration.html#cb465-4" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wine_data[,<span class="dv">7</span>])</span>
<span id="cb465-5"><a href="demonstration.html#cb465-5" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">9</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wine_data[,<span class="dv">9</span>])</span>
<span id="cb465-6"><a href="demonstration.html#cb465-6" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">10</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wine_data[,<span class="dv">10</span>])</span>
<span id="cb465-7"><a href="demonstration.html#cb465-7" tabindex="-1"></a><span class="sc">&gt;</span> wine_data [,<span class="dv">11</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wine_data[,<span class="dv">11</span>])</span>
<span id="cb465-8"><a href="demonstration.html#cb465-8" tabindex="-1"></a><span class="sc">&gt;</span> wine_data <span class="ot">&lt;-</span> wine_data[, <span class="sc">!</span>(<span class="fu">names</span>(wine_data) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;country&quot;</span>))]</span>
<span id="cb465-9"><a href="demonstration.html#cb465-9" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(wine_data)</span></code></pre></div>
<pre><code>##               winery                wine           year          rating     
##  Contino         : 457   Reserva      : 467   Min.   :1910   Min.   :4.200  
##  Artadi          : 261   Gran Reserva : 458   1st Qu.:2011   1st Qu.:4.200  
##  La Rioja Alta   : 254   Rioja Reserva: 240   Median :2015   Median :4.200  
##  Sierra Cantabria: 237   El Viejo     : 224   Mean   :2013   Mean   :4.255  
##  Matarromera     : 232   Corimbo I    : 223   3rd Qu.:2017   3rd Qu.:4.200  
##  Vina Pedrosa    : 230   Mirto        : 223   Max.   :2021   Max.   :4.900  
##  (Other)         :5829   (Other)      :5665   NA&#39;s   :290                   
##   num_reviews                   region         price        
##  Min.   :   25.0   Rioja           :2440   Min.   :   4.99  
##  1st Qu.:  389.0   Ribera del Duero:1413   1st Qu.:  18.90  
##  Median :  404.0   Priorato        : 686   Median :  28.53  
##  Mean   :  451.1   Toro            : 300   Mean   :  60.10  
##  3rd Qu.:  415.0   Vino de Espana  : 263   3rd Qu.:  51.35  
##  Max.   :32624.0   Rias Baixas     : 252   Max.   :3119.08  
##                    (Other)         :2146                    
##                    type        body      acidity    
##  Rioja Red           :2357   2   :  34   1   :  35  
##  Ribera Del Duero Red:1407   3   : 553   2   : 268  
##  Red                 : 864   4   :4120   3   :6028  
##  Priorat Red         : 674   5   :1624   NA&#39;s:1169  
##  Toro Red            : 296   NA&#39;s:1169              
##  (Other)             :1357                          
##  NA&#39;s                : 545</code></pre>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="demonstration.html#cb467-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">dim</span>(wine_data)</span></code></pre></div>
<pre><code>## [1] 7500   10</code></pre>
<p>We have observed the presence of missing values in our dataset. Given the substantial size of our dataset, we can opt to remove rows that contain <code>NA</code> values.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="demonstration.html#cb469-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># contains only the rows where there are no NAs in the specified columns.</span></span>
<span id="cb469-2"><a href="demonstration.html#cb469-2" tabindex="-1"></a><span class="er">&gt;</span> wine_data <span class="ot">&lt;-</span> wine_data[<span class="fu">complete.cases</span>(wine_data[, <span class="fu">c</span>(<span class="st">&quot;body&quot;</span>, <span class="st">&quot;acidity&quot;</span>, <span class="st">&quot;type&quot;</span>)]), ]</span>
<span id="cb469-3"><a href="demonstration.html#cb469-3" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Handle missing values in the &#39;year&#39; variable</span></span>
<span id="cb469-4"><a href="demonstration.html#cb469-4" tabindex="-1"></a><span class="er">&gt;</span> wine_data<span class="sc">$</span>year[<span class="fu">is.na</span>(wine_data<span class="sc">$</span>year)] <span class="ot">&lt;-</span> <span class="fu">median</span>(wine_data<span class="sc">$</span>year, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb469-5"><a href="demonstration.html#cb469-5" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Check the number of missing values after removal</span></span>
<span id="cb469-6"><a href="demonstration.html#cb469-6" tabindex="-1"></a><span class="er">&gt;</span> missing_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(wine_data))</span>
<span id="cb469-7"><a href="demonstration.html#cb469-7" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(missing_values)</span></code></pre></div>
<pre><code>##      winery        wine        year      rating num_reviews      region 
##           0           0           0           0           0           0 
##       price        type        body     acidity 
##           0           0           0           0</code></pre>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="demonstration.html#cb471-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Summary of the dataset</span></span>
<span id="cb471-2"><a href="demonstration.html#cb471-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">summary</span>(wine_data)</span></code></pre></div>
<pre><code>##               winery                 wine           year          rating    
##  Contino         : 414   Reserva       : 422   Min.   :1910   Min.   :4.20  
##  Artadi          : 239   Gran Reserva  : 415   1st Qu.:2011   1st Qu.:4.20  
##  La Rioja Alta   : 228   Rioja Reserva : 218   Median :2015   Median :4.20  
##  Sierra Cantabria: 215   Corimbo I     : 202   Mean   :2013   Mean   :4.26  
##  Vina Pedrosa    : 207   El Viejo      : 202   3rd Qu.:2017   3rd Qu.:4.20  
##  Imperial        : 206   Rioja Graciano: 202   Max.   :2021   Max.   :4.90  
##  (Other)         :4822   (Other)       :4670                                
##   num_reviews                     region         price        
##  Min.   :   25.0   Rioja             :2221   Min.   :   4.99  
##  1st Qu.:  388.0   Ribera del Duero  :1281   1st Qu.:  19.98  
##  Median :  402.0   Priorato          : 622   Median :  29.15  
##  Mean   :  444.1   Toro              : 264   Mean   :  65.71  
##  3rd Qu.:  415.0   Vino de Espana    : 240   3rd Qu.:  60.95  
##  Max.   :32624.0   Jerez-Xeres-Sherry: 225   Max.   :3119.08  
##                    (Other)           :1478                    
##                    type      body     acidity 
##  Rioja Red           :2143   2:  34   1:  35  
##  Ribera Del Duero Red:1278   3: 553   2: 268  
##  Red                 : 787   4:4120   3:6028  
##  Priorat Red         : 620   5:1624           
##  Tempranillo         : 268                    
##  Toro Red            : 261                    
##  (Other)             : 974</code></pre>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="demonstration.html#cb473-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Structure of the dataset</span></span>
<span id="cb473-2"><a href="demonstration.html#cb473-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">glimpse</span>(wine_data)</span></code></pre></div>
<pre><code>## Rows: 6,331
## Columns: 10
## $ winery      &lt;fct&gt; Teso La Monja, Artadi, Vega Sicilia, Vega Sicilia, Vega Si…
## $ wine        &lt;fct&gt; Tinto, Vina El Pison, Unico, Unico, Unico, Unico, Unico, U…
## $ year        &lt;dbl&gt; 2013, 2018, 2009, 1999, 1996, 1998, 2010, 1995, 2015, 2011…
## $ rating      &lt;dbl&gt; 4.9, 4.9, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8…
## $ num_reviews &lt;int&gt; 58, 31, 1793, 1705, 1309, 1209, 1201, 926, 643, 630, 591, …
## $ region      &lt;fct&gt; Toro, Vino de Espana, Ribera del Duero, Ribera del Duero, …
## $ price       &lt;dbl&gt; 995.0000, 313.5000, 324.9500, 692.9600, 778.0600, 490.0000…
## $ type        &lt;fct&gt; Toro Red, Tempranillo, Ribera Del Duero Red, Ribera Del Du…
## $ body        &lt;fct&gt; 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5…
## $ acidity     &lt;fct&gt; 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3…</code></pre>
<p>As we conclude the data preprocessing step, we have transformed character types into factors, changed the year variable to an integer type, and removed the country variable, considering that all wines are from Spain. Additionally, we have addressed missing values by removing rows containing NA values. With these preparations completed, we are now ready to proceed to the next step: Exploratory Data Analysis (EDA), where we will delve deeper into the dataset to gain insights and prepare for the model selection process.</p>
</div>
<div id="exploratory-data-analysis-eda" class="section level2 unnumbered hasAnchor">
<h2>Exploratory Data Analysis (EDA)<a href="demonstration.html#exploratory-data-analysis-eda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Exploratory Data Analysis (EDA) is a crucial step in the data science process that involves exploring and understanding the structure, patterns, and relationships in a dataset. By visually and statistically analysing the data, data scientists can uncover insights, identify patterns, and detect anomalies that can inform subsequent analysis and modelling decisions. In this section, we will perform EDA on the wine dataset to gain a deeper understanding of its features and prepare for the modelling phase. Through visualisations and summary statistics, we aim to uncover meaningful patterns and relationships in the data, which will guide our further analysis and modelling strategies.</p>
<p>Let’s begin by presenting the dataset’s size and complexity, starting with the number of rows and columns. Additionally, we’ll compute summary statistics for numerical variables to gain insights into their distribution and range. This analysis can help us identify potential outliers and better understand the overall structure of the data.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="demonstration.html#cb475-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Display the number of rows and columns</span></span>
<span id="cb475-2"><a href="demonstration.html#cb475-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Number of rows:&quot;</span>, <span class="fu">nrow</span>(wine_data), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Number of rows: 6331</code></pre>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="demonstration.html#cb477-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Number of columns:&quot;</span>, <span class="fu">ncol</span>(wine_data), <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Number of columns: 10</code></pre>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="demonstration.html#cb479-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Statistical summary for numerical variables</span></span>
<span id="cb479-2"><a href="demonstration.html#cb479-2" tabindex="-1"></a><span class="er">&gt;</span> num_vars <span class="ot">&lt;-</span> <span class="fu">sapply</span>(wine_data, is.numeric)</span>
<span id="cb479-3"><a href="demonstration.html#cb479-3" tabindex="-1"></a><span class="sc">&gt;</span> num_data <span class="ot">&lt;-</span> wine_data[, num_vars]</span>
<span id="cb479-4"><a href="demonstration.html#cb479-4" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(num_data)</span></code></pre></div>
<pre><code>##       year          rating      num_reviews          price        
##  Min.   :1910   Min.   :4.20   Min.   :   25.0   Min.   :   4.99  
##  1st Qu.:2011   1st Qu.:4.20   1st Qu.:  388.0   1st Qu.:  19.98  
##  Median :2015   Median :4.20   Median :  402.0   Median :  29.15  
##  Mean   :2013   Mean   :4.26   Mean   :  444.1   Mean   :  65.71  
##  3rd Qu.:2017   3rd Qu.:4.20   3rd Qu.:  415.0   3rd Qu.:  60.95  
##  Max.   :2021   Max.   :4.90   Max.   :32624.0   Max.   :3119.08</code></pre>
<p>From the summary statistics, we can draw the following conclusions:</p>
<ul>
<li><code>year</code>: The wines in the dataset span a wide range of years, from 1910 to 2021, with the majority falling between 2011 and 2017.<br />
</li>
<li><code>rating</code>: The ratings for the wines range from 4.2 to 4.9, with an average rating of approximately 4.26. The ratings appear to be quite high, with the median also at 4.2.<br />
</li>
<li><code>num_reviews</code>: The number of reviews for the wines varies widely, with a minimum of 25 reviews and a maximum of 16505 reviews. The average number of reviews is approximately 440, indicating that some wines have received significant attention and feedback.<br />
</li>
<li><code>price</code>: The prices of the wines range from 6.26 to 3119.08, with an average price of approximately 67.40. However, the distribution of prices appears to be skewed, as the median price is 31.63, which is much lower than the mean.</li>
</ul>
<p>Now, we will utilise ChatGPT to aid us in conducting Exploratory Data Analysis (EDA) on the <code>wine_data</code> dataset. Through a combination of visualisations and statistical analyses, we aim to explore the distribution of key numerical variables such as rating, num_reviews, and price. Additionally, we will investigate the potential impact of categorical variables such as region, type and acidity on these key metrics.</p>
<p><span style="color:red"><strong>Prompt:</strong> </span> <span style="color:gray">
Please provide an R code for creating visually appealing visualisations of key numerical variables such as rating, num_reviews, and price. Additionally, analyse the potential impact of categorical variables such as region, and type on these key metrics. The dataset has a structure of 6,331 rows and 10 columns, with variables including winery, wine, year, rating, num_reviews, region, price, type, body, and acidity.</span></p>
<pre><code>&gt; glimpse(wine_data)
Rows: 6,331
Columns: 10
$ winery      &lt;fct&gt; Teso La Monja, Artadi, Vega…
$ wine        &lt;fct&gt; Tinto, Vina El Pison, Unico…
$ year        &lt;dbl&gt; 2013, 2018, 2009, 1999, 199…
$ rating      &lt;dbl&gt; 4.9, 4.9, 4.8, 4.8, 4.8, 4.…
$ num_reviews &lt;int&gt; 58, 31, 1793, 1705, 1309, 1…
$ region      &lt;fct&gt; Toro, Vino de Espana, Riber…
$ price       &lt;dbl&gt; 995.00, 313.50, 324.95, 692…
$ type        &lt;fct&gt; Toro Red, Tempranillo, Ribe…
$ body        &lt;fct&gt; 5, 4, 5, 5, 5, 5, 5, 5, 5, …
$ acidity     &lt;fct&gt; 3, 2, 3, 3, 3, 3, 3, 3, 3, …</code></pre>
<p>❗️<span style="color:green"> Make sure to include the <code>glimpse()</code> output in your prompt question to give an overview of your data’s structure!</span></p>
<p><span style="color:red"><strong>ChatGPT</strong></span>
<img src="images/prompt2.gif" width="85%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="demonstration.html#cb482-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Create visualisations</span></span>
<span id="cb482-2"><a href="demonstration.html#cb482-2" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb482-3"><a href="demonstration.html#cb482-3" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Histogram of Ratings</span></span>
<span id="cb482-4"><a href="demonstration.html#cb482-4" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(wine_data, <span class="fu">aes</span>(<span class="at">x =</span> rating)) <span class="sc">+</span> </span>
<span id="cb482-5"><a href="demonstration.html#cb482-5" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb482-6"><a href="demonstration.html#cb482-6" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of Ratings&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Rating&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="demonstration.html#cb483-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Histogram of Price</span></span>
<span id="cb483-2"><a href="demonstration.html#cb483-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(wine_data, <span class="fu">aes</span>(<span class="at">x =</span> price)) <span class="sc">+</span> </span>
<span id="cb483-3"><a href="demonstration.html#cb483-3" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb483-4"><a href="demonstration.html#cb483-4" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of Wine Prices&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Price&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="demonstration.html#cb484-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Scatterplot of Rating vs. Num_reviews</span></span>
<span id="cb484-2"><a href="demonstration.html#cb484-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(wine_data, <span class="fu">aes</span>(<span class="at">x =</span> num_reviews, <span class="at">y =</span> rating)) <span class="sc">+</span> </span>
<span id="cb484-3"><a href="demonstration.html#cb484-3" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;skyblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb484-4"><a href="demonstration.html#cb484-4" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Rating vs. Number of Reviews&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Number of Reviews&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Rating&quot;</span>)</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="demonstration.html#cb485-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Barplot of Wine Types</span></span>
<span id="cb485-2"><a href="demonstration.html#cb485-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(wine_data, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">fill =</span> type)) <span class="sc">+</span> </span>
<span id="cb485-3"><a href="demonstration.html#cb485-3" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb485-4"><a href="demonstration.html#cb485-4" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of Wine Types&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Type&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb485-5"><a href="demonstration.html#cb485-5" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb485-6"><a href="demonstration.html#cb485-6" tabindex="-1"></a><span class="sc">+</span>         <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-5-4.png" width="672" /></p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="demonstration.html#cb486-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Barplot of Regions</span></span>
<span id="cb486-2"><a href="demonstration.html#cb486-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(wine_data, <span class="fu">aes</span>(<span class="at">x =</span> region, <span class="at">fill =</span> region)) <span class="sc">+</span> </span>
<span id="cb486-3"><a href="demonstration.html#cb486-3" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb486-4"><a href="demonstration.html#cb486-4" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribution of Regions&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Region&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb486-5"><a href="demonstration.html#cb486-5" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb486-6"><a href="demonstration.html#cb486-6" tabindex="-1"></a><span class="sc">+</span>         <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-5-5.png" width="672" /></p>
<p>The Barplot of Regions is challenging to interpret due to the numerous regions displayed. Since there are too many regions to effectively visualise, let’s seek assistance from ChatGPT for a solution.</p>
<p><span style="color:red"><strong>Prompt:</strong> </span>Please filter and display only the top 10 regions for better clarity in this visualization.</p>
<pre><code>ggplot(wine_data, aes(x = region, fill = region)) + 
  geom_bar() +
  labs(title = &quot;Distribution of Regions&quot;, x = &quot;Region&quot;, y = &quot;Count&quot;) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = &quot;none&quot;)</code></pre>
<p><span style="color:gray"></p>
<p>❗️<span style="color:green"> Once more, please ensure that the code is included to enhance clarity</span></p>
<p><span style="color:red"><strong>ChatGPT</strong></span>
<img src="images/prompt3.png" width="85%" style="display: block; margin: auto;" /></p>
<p>We can enhance the ggplot by removing the legend, as the region names are already displayed below the bars.</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="demonstration.html#cb488-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Get the top 10 regions by frequency</span></span>
<span id="cb488-2"><a href="demonstration.html#cb488-2" tabindex="-1"></a><span class="er">&gt;</span> top_regions <span class="ot">&lt;-</span> wine_data <span class="sc">%&gt;%</span></span>
<span id="cb488-3"><a href="demonstration.html#cb488-3" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb488-4"><a href="demonstration.html#cb488-4" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb488-5"><a href="demonstration.html#cb488-5" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">arrange</span>(<span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span></span>
<span id="cb488-6"><a href="demonstration.html#cb488-6" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb488-7"><a href="demonstration.html#cb488-7" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Filter the dataset to include only the top 10 regions</span></span>
<span id="cb488-8"><a href="demonstration.html#cb488-8" tabindex="-1"></a><span class="er">&gt;</span> wine_data_top_regions <span class="ot">&lt;-</span> wine_data <span class="sc">%&gt;%</span></span>
<span id="cb488-9"><a href="demonstration.html#cb488-9" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(region <span class="sc">%in%</span> top_regions<span class="sc">$</span>region)</span>
<span id="cb488-10"><a href="demonstration.html#cb488-10" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Barplot of Top 10 Regions</span></span>
<span id="cb488-11"><a href="demonstration.html#cb488-11" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(wine_data_top_regions, <span class="fu">aes</span>(<span class="at">x =</span> region, <span class="at">fill =</span> region)) <span class="sc">+</span> </span>
<span id="cb488-12"><a href="demonstration.html#cb488-12" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb488-13"><a href="demonstration.html#cb488-13" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Top 10 Regions by Frequency&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Region&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb488-14"><a href="demonstration.html#cb488-14" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb488-15"><a href="demonstration.html#cb488-15" tabindex="-1"></a><span class="sc">+</span>         <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Let’s assess the degree of association between the key variables. To do this, we’ll need to convert the variables ‘body’ and ‘acidity’.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="demonstration.html#cb489-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Convert factors to numeric (if appropriate)</span></span>
<span id="cb489-2"><a href="demonstration.html#cb489-2" tabindex="-1"></a><span class="er">&gt;</span> wine_data<span class="sc">$</span>body <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(wine_data<span class="sc">$</span>body))</span>
<span id="cb489-3"><a href="demonstration.html#cb489-3" tabindex="-1"></a><span class="sc">&gt;</span> wine_data<span class="sc">$</span>acidity <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(wine_data<span class="sc">$</span>acidity))</span>
<span id="cb489-4"><a href="demonstration.html#cb489-4" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb489-5"><a href="demonstration.html#cb489-5" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Compute the correlation matrix</span></span>
<span id="cb489-6"><a href="demonstration.html#cb489-6" tabindex="-1"></a><span class="er">&gt;</span> correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(wine_data[, <span class="fu">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;rating&quot;</span>, <span class="st">&quot;num_reviews&quot;</span>, <span class="st">&quot;price&quot;</span>, <span class="st">&quot;body&quot;</span>, <span class="st">&quot;acidity&quot;</span>)])</span>
<span id="cb489-7"><a href="demonstration.html#cb489-7" tabindex="-1"></a><span class="sc">&gt;</span> correlation_matrix</span></code></pre></div>
<pre><code>##                    year        rating   num_reviews       price        body
## year         1.00000000 -0.2957784867  0.0354872722 -0.38526005 -0.10277253
## rating      -0.29577849  1.0000000000 -0.0001653593  0.55209571  0.16303349
## num_reviews  0.03548727 -0.0001653593  1.0000000000 -0.03393994  0.06710569
## price       -0.38526005  0.5520957084 -0.0339399360  1.00000000  0.15362352
## body        -0.10277253  0.1630334935  0.0671056895  0.15362352  1.00000000
## acidity      0.14806938 -0.0945527010  0.0401375039 -0.03286992 -0.01795032
##                 acidity
## year         0.14806938
## rating      -0.09455270
## num_reviews  0.04013750
## price       -0.03286992
## body        -0.01795032
## acidity      1.00000000</code></pre>
<p>Let us ask chatGPT to visualise this outcome.</p>
<p><span style="color:red"><strong>Prompt:</strong> </span> <span style="color:gray">Please provide R code to create a heatmap visualising the correlation matrix shown below. Ensure the heatmap includes a gradient color scheme, correlation coefficients, axis labels, and a title.</span></p>
<pre><code>&gt; correlation_matrix
                   year        rating   num_reviews       price
year         1.00000000 -0.2957784867  0.0354872722 -0.38526005
rating      -0.29577849  1.0000000000 -0.0001653593  0.55209571
num_reviews  0.03548727 -0.0001653593  1.0000000000 -0.03393994
price       -0.38526005  0.5520957084 -0.0339399360  1.00000000
body        -0.10277253  0.1630334935  0.0671056895  0.15362352
acidity      0.14806938 -0.0945527010  0.0401375039 -0.03286992
                   body     acidity
year        -0.10277253  0.14806938
rating       0.16303349 -0.09455270
num_reviews  0.06710569  0.04013750
price        0.15362352 -0.03286992
body         1.00000000 -0.01795032
acidity     -0.01795032  1.00000000</code></pre>
<p><span style="color:red"><strong>ChatGPT</strong></span>
<img src="images/prompt4.png" width="85%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="demonstration.html#cb492-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Create a heatmap of the correlation matrix with correlation coefficients</span></span>
<span id="cb492-2"><a href="demonstration.html#cb492-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">melt</span>(correlation_matrix), <span class="fu">aes</span>(<span class="at">x=</span>Var1, <span class="at">y=</span>Var2, <span class="at">fill=</span>value)) <span class="sc">+</span></span>
<span id="cb492-3"><a href="demonstration.html#cb492-3" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb492-4"><a href="demonstration.html#cb492-4" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(value, <span class="dv">2</span>)), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  <span class="co"># Add text labels for correlation coefficients</span></span>
<span id="cb492-5"><a href="demonstration.html#cb492-5" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">scale_fill_gradient2</span>(<span class="at">low=</span><span class="st">&quot;blue&quot;</span>, <span class="at">mid=</span><span class="st">&quot;white&quot;</span>, <span class="at">high=</span><span class="st">&quot;red&quot;</span>, <span class="at">midpoint=</span><span class="dv">0</span>, <span class="at">limit=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb492-6"><a href="demonstration.html#cb492-6" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb492-7"><a href="demonstration.html#cb492-7" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;Correlation Heatmap&quot;</span>, <span class="at">x=</span><span class="st">&quot;Variables&quot;</span>, <span class="at">y=</span><span class="st">&quot;Variables&quot;</span>) <span class="sc">+</span></span>
<span id="cb492-8"><a href="demonstration.html#cb492-8" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The correlation matrix offers valuable insights into the relationship between wine attributes and prices. It reveals that older wines tend to be less expensive, as seen in the negative correlation between year and price. Conversely, higher-rated wines are associated with higher prices, supported by the positive correlation between rating and price. Surprisingly, there is almost no relationship between the number of reviews or acidity and price, suggesting limited impact on pricing decisions. Additionally, wines with a higher body may command slightly higher prices, indicated by a weak positive correlation. Overall, the rating emerges as the strongest predictor of wine price, underscoring the significance of quality perception in pricing strategies.</p>
<p>In conclusion, the EDA phase has shed light on the key variables influencing wine prices. Factors such as the year of production, wine rating, and body appear to be significant determinants. However, variables like the number of reviews and acidity show minimal impact. With these insights, we can now transition to the next phase: model selection and training. This step will involve choosing suitable models to predict wine prices based on the identified variables and training them on our dataset to make accurate price predictions.</p>
</div>
<div id="model-selection-and-model-training" class="section level2 unnumbered hasAnchor">
<h2>Model Selection and Model Training<a href="demonstration.html#model-selection-and-model-training" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Model selection and training are pivotal stages in any data analysis project, especially when predicting intricate phenomena like wine prices. During this phase, we will leverage the insights gleaned from our exploratory data analysis (EDA) to select the most appropriate machine learning models for predicting wine prices. Our goal is to choose models that can adeptly capture the relationships between key variables identified in the EDA, thereby crafting robust and accurate models for predicting wine prices. This process will entail evaluating various regression models, including linear regression, lasso regression, ridge regression, regression tree, and Generalized Additive Model (GAM), to ascertain which one performs optimally for our dataset. Through the process of model selection and training, our aim is to develop a dependable pricing model that can facilitate stakeholders in making well-informed decisions within the wine industry.</p>
<p>However, considering that certain attribute variables in <code>wine_data</code> comprise a large number of levels, we will exclude the fitting of the multiple regression model. Linear models assume a linear relationship between the predictors and the outcome variable, which can be challenging when dealing with numerous factor levels. In such instances, the model may attempt to fit each level individually, leading to overfitting and a lack of generalisation to new data. Furthermore, estimating coefficients for each factor level can be computationally intensive and may not be viable for sizable datasets. The interpretation of coefficients in a linear model with many factor levels can also be intricate, making it challenging to discern the impact of each level on the outcome variable. Therefore, alternative modeling techniques that can effectively handle factor variables with a large number of levels, such as tree-based models, may be more suitable in these scenarios.</p>
<p>So, let us start by asking chatGPT to build for us those suggested models.</p>
<p><span style="color:red"><strong>Prompt:</strong> </span> <span style="color:gray">Perform machine learning to predict wine prices using lasso regression, ridge regression, regression tree, and Generalized Additive Model (GAM) to identify the most effective model for the wine_data dataset.</span></p>
<pre><code>&gt; glimpse(wine_data)
Rows: 6,331
Columns: 10
$ winery      &lt;fct&gt; Teso La Monja, Artadi, Vega…
$ wine        &lt;fct&gt; Tinto, Vina El Pison, Unico…
$ year        &lt;dbl&gt; 2013, 2018, 2009, 1999, 199…
$ rating      &lt;dbl&gt; 4.9, 4.9, 4.8, 4.8, 4.8, 4.…
$ num_reviews &lt;int&gt; 58, 31, 1793, 1705, 1309, 1…
$ region      &lt;fct&gt; Toro, Vino de Espana, Riber…
$ price       &lt;dbl&gt; 995.00, 313.50, 324.95, 692…
$ type        &lt;fct&gt; Toro Red, Tempranillo, Ribe…
$ body        &lt;dbl&gt; 5, 4, 5, 5, 5, 5, 5, 5, 5, …
$ acidity     &lt;dbl&gt; 3, 2, 3, 3, 3, 3, 3, 3, 3, …</code></pre>
<p><span style="color:red"><strong>ChatGPT</strong></span>
<img src="images/prompt5.png" width="85%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="demonstration.html#cb494-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Set seed for reproducibility</span></span>
<span id="cb494-2"><a href="demonstration.html#cb494-2" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb494-3"><a href="demonstration.html#cb494-3" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb494-4"><a href="demonstration.html#cb494-4" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Split the data into training and testing sets</span></span>
<span id="cb494-5"><a href="demonstration.html#cb494-5" tabindex="-1"></a><span class="er">&gt;</span> train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(wine_data), <span class="fl">0.7</span> <span class="sc">*</span> <span class="fu">nrow</span>(wine_data))</span>
<span id="cb494-6"><a href="demonstration.html#cb494-6" tabindex="-1"></a><span class="sc">&gt;</span> train_data <span class="ot">&lt;-</span> wine_data[train_indices, ]</span>
<span id="cb494-7"><a href="demonstration.html#cb494-7" tabindex="-1"></a><span class="sc">&gt;</span> test_data <span class="ot">&lt;-</span> wine_data[<span class="sc">-</span>train_indices, ]</span>
<span id="cb494-8"><a href="demonstration.html#cb494-8" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb494-9"><a href="demonstration.html#cb494-9" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Fit lasso regression</span></span>
<span id="cb494-10"><a href="demonstration.html#cb494-10" tabindex="-1"></a><span class="er">&gt;</span> lasso_model <span class="ot">&lt;-</span> glmnet<span class="sc">::</span><span class="fu">glmnet</span>(<span class="fu">as.matrix</span>(<span class="fu">select</span>(train_data, <span class="sc">-</span>price)), train_data<span class="sc">$</span>price, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb494-11"><a href="demonstration.html#cb494-11" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb494-12"><a href="demonstration.html#cb494-12" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Fit ridge regression</span></span>
<span id="cb494-13"><a href="demonstration.html#cb494-13" tabindex="-1"></a><span class="er">&gt;</span> ridge_model <span class="ot">&lt;-</span> glmnet<span class="sc">::</span><span class="fu">glmnet</span>(<span class="fu">as.matrix</span>(<span class="fu">select</span>(train_data, <span class="sc">-</span>price)), train_data<span class="sc">$</span>price, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb494-14"><a href="demonstration.html#cb494-14" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb494-15"><a href="demonstration.html#cb494-15" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Fit regression tree</span></span>
<span id="cb494-16"><a href="demonstration.html#cb494-16" tabindex="-1"></a><span class="er">&gt;</span> tree_model <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">rpart</span>(price <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb494-17"><a href="demonstration.html#cb494-17" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb494-18"><a href="demonstration.html#cb494-18" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Fit Generalized Additive Model (GAM)</span></span>
<span id="cb494-19"><a href="demonstration.html#cb494-19" tabindex="-1"></a><span class="er">&gt;</span> gam_model <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(price <span class="sc">~</span> <span class="fu">bs</span>(year, <span class="at">df =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">bs</span>(rating, <span class="at">df =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">bs</span>(num_reviews, <span class="at">df =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">bs</span>(body, <span class="at">df =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">bs</span>(acidity, <span class="at">df =</span> <span class="dv">3</span>), <span class="at">data =</span> train_data)</span></code></pre></div>
<p>In this section, we fitted various models for predicting wine prices, including lasso regression, ridge regression, regression tree, and Generalized Additive Model (GAM). Each model offers unique advantages and complexities, making it crucial to select the most suitable one for our dataset. Following model selection and training, the next step is to evaluate the performance of these models to determine which one best predicts wine prices. This evaluation will provide insights into the model’s accuracy and reliability, guiding us in making informed decisions about the most effective model for our wine_data dataset.</p>
</div>
<div id="model-evaluation" class="section level2 unnumbered hasAnchor">
<h2>Model Evaluation<a href="demonstration.html#model-evaluation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the Model Evaluation section, we assess the performance of various machine learning models in predicting wine prices for the <code>wine_data</code> dataset. By examining metrics such as RMSE and MAE, we aim to determine the most accurate and reliable model for our predictive tasks. This evaluation will provide valuable insights into the effectiveness of each model and guide us in selecting the best approach for predicting wine prices.</p>
<p>We will ask chatGPT to generate the code for this task.</p>
<p><span style="color:red"><strong>Prompt:</strong> </span> <span style="color:gray">Please generate R code to evaluate the performance of the fitted models (lasso regression, ridge regression, regression tree, and Generalized Additive Model) on the test dataset. Compute and print the RMSE and MAE for each model in the code given to assess their predictive accuracy.</span></p>
<pre><code># Set seed for reproducibility
set.seed(123)

# Split the data into training and testing sets
train_indices &lt;- sample(1:nrow(wine_data), 0.7 * nrow(wine_data))
train_data &lt;- wine_data[train_indices, ]
test_data &lt;- wine_data[-train_indices, ]

# Fit lasso regression
lasso_model &lt;- glmnet::glmnet(as.matrix(select(train_data, -price)), train_data$price, alpha = 1)

# Fit ridge regression
ridge_model &lt;- glmnet::glmnet(as.matrix(select(train_data, -price)), train_data$price, alpha = 0)

# Fit regression tree
tree_model &lt;- rpart::rpart(price ~ ., data = train_data)

# Fit Generalized Additive Model (GAM)
gam_model &lt;- mgcv::gam(price ~ bs(year, df = 3) + bs(rating, df = 3) + bs(num_reviews, df = 3) + bs(body, df = 3) + bs(acidity, df = 3), data = train_data)</code></pre>
<p><span style="color:red"><strong>ChatGPT</strong></span>
<img src="images/prompt6.gif" width="85%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="demonstration.html#cb496-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Predictions for lasso regression</span></span>
<span id="cb496-2"><a href="demonstration.html#cb496-2" tabindex="-1"></a><span class="er">&gt;</span> lasso_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lasso_model, <span class="at">newx =</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(test_data, <span class="sc">-</span>price)))</span>
<span id="cb496-3"><a href="demonstration.html#cb496-3" tabindex="-1"></a><span class="sc">&gt;</span> lasso_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((lasso_pred <span class="sc">-</span> test_data<span class="sc">$</span>price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb496-4"><a href="demonstration.html#cb496-4" tabindex="-1"></a><span class="sc">&gt;</span> lasso_mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(lasso_pred <span class="sc">-</span> test_data<span class="sc">$</span>price))</span>
<span id="cb496-5"><a href="demonstration.html#cb496-5" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb496-6"><a href="demonstration.html#cb496-6" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Predictions for ridge regression</span></span>
<span id="cb496-7"><a href="demonstration.html#cb496-7" tabindex="-1"></a><span class="er">&gt;</span> ridge_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ridge_model, <span class="at">newx =</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(test_data, <span class="sc">-</span>price)))</span>
<span id="cb496-8"><a href="demonstration.html#cb496-8" tabindex="-1"></a><span class="sc">&gt;</span> ridge_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((ridge_pred <span class="sc">-</span> test_data<span class="sc">$</span>price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb496-9"><a href="demonstration.html#cb496-9" tabindex="-1"></a><span class="sc">&gt;</span> ridge_mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(ridge_pred <span class="sc">-</span> test_data<span class="sc">$</span>price))</span>
<span id="cb496-10"><a href="demonstration.html#cb496-10" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb496-11"><a href="demonstration.html#cb496-11" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Predictions for regression tree</span></span>
<span id="cb496-12"><a href="demonstration.html#cb496-12" tabindex="-1"></a><span class="er">&gt;</span> tree_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb496-13"><a href="demonstration.html#cb496-13" tabindex="-1"></a><span class="sc">&gt;</span> tree_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((tree_pred <span class="sc">-</span> test_data<span class="sc">$</span>price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb496-14"><a href="demonstration.html#cb496-14" tabindex="-1"></a><span class="sc">&gt;</span> tree_mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(tree_pred <span class="sc">-</span> test_data<span class="sc">$</span>price))</span>
<span id="cb496-15"><a href="demonstration.html#cb496-15" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb496-16"><a href="demonstration.html#cb496-16" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Predictions for GAM</span></span>
<span id="cb496-17"><a href="demonstration.html#cb496-17" tabindex="-1"></a><span class="er">&gt;</span> gam_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(gam_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb496-18"><a href="demonstration.html#cb496-18" tabindex="-1"></a><span class="sc">&gt;</span> gam_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((gam_pred <span class="sc">-</span> test_data<span class="sc">$</span>price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb496-19"><a href="demonstration.html#cb496-19" tabindex="-1"></a><span class="sc">&gt;</span> gam_mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(gam_pred <span class="sc">-</span> test_data<span class="sc">$</span>price))</span>
<span id="cb496-20"><a href="demonstration.html#cb496-20" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb496-21"><a href="demonstration.html#cb496-21" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Print RMSE and MAE for each model</span></span>
<span id="cb496-22"><a href="demonstration.html#cb496-22" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Lasso Regression RMSE:&quot;</span>, lasso_rmse, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Lasso Regression RMSE: 142.121</code></pre>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="demonstration.html#cb498-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Lasso Regression MAE:&quot;</span>, lasso_mae, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Lasso Regression MAE: 47.67765</code></pre>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="demonstration.html#cb500-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Ridge Regression RMSE:&quot;</span>, ridge_rmse, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Ridge Regression RMSE: 160.9951</code></pre>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="demonstration.html#cb502-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Ridge Regression MAE:&quot;</span>, ridge_mae, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Ridge Regression MAE: 52.27333</code></pre>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="demonstration.html#cb504-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Regression Tree RMSE:&quot;</span>, tree_rmse, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Regression Tree RMSE: 88.45144</code></pre>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="demonstration.html#cb506-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Regression Tree MAE:&quot;</span>, tree_mae, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Regression Tree MAE: 24.06545</code></pre>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="demonstration.html#cb508-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Generalized Additive Model RMSE:&quot;</span>, gam_rmse, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Generalized Additive Model RMSE: 123.112</code></pre>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="demonstration.html#cb510-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">cat</span>(<span class="st">&quot;Generalized Additive Model MAE:&quot;</span>, gam_mae, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Generalized Additive Model MAE: 40.67011</code></pre>
<p>We can consolidate the results and display them in a unified table for easier comparison.</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="demonstration.html#cb512-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Combine results into a table</span></span>
<span id="cb512-2"><a href="demonstration.html#cb512-2" tabindex="-1"></a><span class="er">&gt;</span> results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb512-3"><a href="demonstration.html#cb512-3" tabindex="-1"></a><span class="sc">+</span>   <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;Lasso Regression&quot;</span>, <span class="st">&quot;Ridge Regression&quot;</span>, <span class="st">&quot;Regression Tree&quot;</span>, <span class="st">&quot;Generalized Additive Model&quot;</span>),</span>
<span id="cb512-4"><a href="demonstration.html#cb512-4" tabindex="-1"></a><span class="sc">+</span>   <span class="at">RMSE =</span> <span class="fu">c</span>(lasso_rmse, ridge_rmse, tree_rmse, gam_rmse),</span>
<span id="cb512-5"><a href="demonstration.html#cb512-5" tabindex="-1"></a><span class="sc">+</span>   <span class="at">MAE =</span> <span class="fu">c</span>(lasso_mae, ridge_mae, tree_mae, gam_mae)</span>
<span id="cb512-6"><a href="demonstration.html#cb512-6" tabindex="-1"></a><span class="sc">+</span> )</span>
<span id="cb512-7"><a href="demonstration.html#cb512-7" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb512-8"><a href="demonstration.html#cb512-8" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Print the table</span></span>
<span id="cb512-9"><a href="demonstration.html#cb512-9" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">print</span>(results)</span></code></pre></div>
<pre><code>##                        Model      RMSE      MAE
## 1           Lasso Regression 142.12096 47.67765
## 2           Ridge Regression 160.99508 52.27333
## 3            Regression Tree  88.45144 24.06545
## 4 Generalized Additive Model 123.11196 40.67011</code></pre>
<p>Upon analysis, it becomes evident that the Regression Tree model outperforms other models in this dataset, particularly due to its ability to handle numerous features effectively. This conclusion is drawn from a comparative evaluation of the models, highlighting the Regression Tree’s superior performance in managing the complexity of the dataset’s features.</p>
</div>
<div id="model-interpretation" class="section level2 unnumbered hasAnchor">
<h2>Model Interpretation<a href="demonstration.html#model-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the model interpretation section of this report, we delve into the insights gained from the trained machine learning models, aiming to understand the underlying factors that influence wine prices. By analysing the feature importance, decision rules, and predicted values of the models, we seek to unravel the complex relationships between wine characteristics and their market values. This section not only sheds light on the predictive performance of the models but also provides actionable insights for stakeholders in the wine industry, guiding them in making informed decisions related to pricing strategies and product development.</p>
<p>We will begin by plotting the regression tree for the <code>wine_data</code>, providing a visual representation of the decision-making process of the model. You can interpret the tree by starting at the root node and following the branches to the leaf nodes, where the predictions are made. Each split in the tree represents a decision based on a feature in the dataset, and the leaf nodes represent the predicted wine prices.</p>
<p>Let us visualise the tree.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="demonstration.html#cb514-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">rpart.plot</span>(tree_model, </span>
<span id="cb514-2"><a href="demonstration.html#cb514-2" tabindex="-1"></a><span class="sc">+</span>             <span class="at">box.palette =</span> <span class="st">&quot;RdBu&quot;</span>, </span>
<span id="cb514-3"><a href="demonstration.html#cb514-3" tabindex="-1"></a><span class="sc">+</span>             <span class="at">shadow.col =</span> <span class="st">&quot;gray&quot;</span>, </span>
<span id="cb514-4"><a href="demonstration.html#cb514-4" tabindex="-1"></a><span class="sc">+</span>             <span class="at">nn =</span> <span class="cn">TRUE</span>, </span>
<span id="cb514-5"><a href="demonstration.html#cb514-5" tabindex="-1"></a><span class="sc">+</span>             <span class="at">type =</span> <span class="dv">4</span>, </span>
<span id="cb514-6"><a href="demonstration.html#cb514-6" tabindex="-1"></a><span class="sc">+</span>             <span class="at">fallen.leaves =</span> <span class="cn">TRUE</span>, </span>
<span id="cb514-7"><a href="demonstration.html#cb514-7" tabindex="-1"></a><span class="sc">+</span>             <span class="at">branch.lty =</span> <span class="dv">3</span>, </span>
<span id="cb514-8"><a href="demonstration.html#cb514-8" tabindex="-1"></a><span class="sc">+</span>             <span class="at">branch.lwd =</span> <span class="dv">2</span>,</span>
<span id="cb514-9"><a href="demonstration.html#cb514-9" tabindex="-1"></a><span class="sc">+</span>             <span class="at">extra =</span> <span class="dv">1</span>,</span>
<span id="cb514-10"><a href="demonstration.html#cb514-10" tabindex="-1"></a><span class="sc">+</span>             <span class="at">cex =</span> <span class="fl">0.6</span>,  <span class="co"># Reduce the size of nodes and text</span></span>
<span id="cb514-11"><a href="demonstration.html#cb514-11" tabindex="-1"></a><span class="sc">+</span>             <span class="at">faclen =</span> <span class="dv">3</span>)  <span class="co"># Adjust the faclen value to increase space between nodes</span></span></code></pre></div>
<p><img src="08-S08-D1_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="demonstration.html#cb515-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(tree_model)</span></code></pre></div>
<pre><code>## Call:
## rpart::rpart(formula = price ~ ., data = train_data)
##   n= 4431 
## 
##           CP nsplit rel error    xerror       xstd
## 1 0.54735715      0 1.0000000 1.0006206 0.17076673
## 2 0.08338496      1 0.4526429 0.5384705 0.10301520
## 3 0.07689143      2 0.3692579 0.5090425 0.09812500
## 4 0.03461715      3 0.2923665 0.4213455 0.08404526
## 5 0.03452879      4 0.2577493 0.4161366 0.08524950
## 6 0.01482093      5 0.2232205 0.3842724 0.08380711
## 7 0.01208131      6 0.2083996 0.3696184 0.08374828
## 8 0.01148682      7 0.1963183 0.3525272 0.08166889
## 9 0.01000000      8 0.1848315 0.3686921 0.08631320
## 
## Variable importance
##        wine      winery      region        type        year num_reviews 
##          57          19           6           5           5           3 
##        body      rating 
##           3           2 
## 
## Node number 1: 4431 observations,    complexity param=0.5473571
##   mean=63.84701, MSE=24260.23 
##   left son=2 (4358 obs) right son=3 (73 obs)
##   Primary splits:
##       wine        splits as  --LLL--LLL--LLLLLLLLLLLL-LL--LLLL-LLL--LLLL--LLLLL-LLLLL-LLLLLLLL-LL-LLL-LLL--LLLLL--L--LL-L--LLLL---LL-LL--LLLLLL-LLLL-LLLLLLLLLL-L-LL-LLLL-L--LLLL-L-LLLLL-LLLLLLLLLLLL-LLLLLLLLLLLLLLLL---LLLLRL-LL-LL-LL-LLLL---LLLLLLLL-LL--L--LLLLLLLLLLL--LLL-LLL--LLLLLL--LLLLL----LL-LLL-LLL-L-L-LLLLLLLLL-LLL-LLLLLLL--LLLL--L-L-L-L-LLL-LLLL-LL-R-L--LLL-L-LLLLLLLL-LLLLL-L-L-LLL-LL-L-L---LLL--L-LLLL-L-R-LLLLLLLLL--LLLRLLL-L-LLLLLL-----L----L--LLLL-L--LLLLL-LLL--L--LLLL-LLLLLLLLL--LLL--LLLLL--LLLL--LL-LLLLLLLLL--LL-LL-LL-LLL--L--LL-L-L--L--LL--L--LL-LL-LLLLL-LLL-LLLLLLLL-L-L-LLL-LLL-LL-LLLL--LRL--LL-L-LLLL-L-LLLLL-LL-L--LLL-LLL--LLLLLLLLLLLL-LL-LLLLL-LLL-RLLL-LLLLLLL-L-LLLLLLLLLLLL---LLL---LLLL---L-L---LLLLLLLLLLL----LLLL---L-LLLLLLLLLLL-L---L-LL-LLLLL-LLLR-LLL-LLLL-LLLLLL--LLL--L-LLL-RRL-L-LL--LL-LLL---LL-L-L-L----LLLLLLLLL-LLLL-LLLLLLL-L-LLL-LL-LLLLLL, improve=0.5473571, (0 missing)
##       winery      splits as  -LLLLLLLLLLL-LL-LLLLLLLLRL-LLLLLLLLLLL---L-LLL--L--LLLL---LL-LLRL-L--LLLL-L-LLLLL-LLLL-LL-LLLL-LLLLLLLLLLLLL---LL-LLLLLL-----L-L-LL-LLL-LLLLLL-LLL-LLRLLLLLLLLLLLLLL-LL-LLLR---LLLL-L--RLL-LL-LLLLL-L-L-LL-LL-LLLLLL-L-LL-LLLL--L-LL-L-LLLLL--L-LLLLLLLLL-L-LL-LLLLL-LLLLL-LLLLLL-L--L-LL-LLLLLL-LL--LLLLL-LLLL--LLL--LLLLLLLLL-LLLLLLLL-LLL-L-LLLL-R--LLLLLLLLLL-LLLL-LLLL-LLL---LLL-L-LLLLLLL-L--LLLLLLLLLLLL--L--LL-LLLLL----LL-RLLLRLLLL-LL-LLL-L-LLLL-LLLLLR--LLLLLL-LLLLLL-LLL-L-LLLLL-L-L, improve=0.3886168, (0 missing)
##       rating      &lt; 4.55   to the left,  improve=0.3049241, (0 missing)
##       year        &lt; 2003.5 to the right, improve=0.1302212, (0 missing)
##       num_reviews &lt; 325.5  to the right, improve=0.1113139, (0 missing)
##   Surrogate splits:
##       winery splits as  -LLLLLLLLLLL-LL-LLLLLLLLLL-LLLLLLLLLLL---L-LLL--L--LLLL---LL-LLRL-L--LLLL-L-LLLLL-LLLL-LL-LLLL-LLLLLLLLLLLLL---LL-LLLLLL-----L-L-LL-LLL-LLLLLL-LLL-LLLLLLLLLLLLLLLLL-LL-LLLR---LLLL-L--LLL-LL-LLLLL-L-L-LL-LL-LLLLLL-L-LL-LLLL--L-LL-L-LLLLL--L-LLLLLLLLL-L-LL-LLLLL-LLLLL-LLLLLL-L--L-LL-LLLLLL-LL--LLLLL-LLLL--LLL--LLLLLLLLL-LLLLLLLL-LLL-L-LLLL-L--LLLLLLLLLL-LLLL-LLLL-LLL---LLL-L-LLLLLLL-L--LLLLLLLLLLLL--L--LL-LLLLL----LL-LLLLLLLLL-LL-LLL-L-LLLL-LLLLLR--LLLLLL-LLLLLL-LLL-L-LLLLL-L-L, agree=0.988, adj=0.274, (0 split)
##       rating &lt; 4.75   to the left,  agree=0.984, adj=0.014, (0 split)
## 
## Node number 2: 4358 observations,    complexity param=0.07689143
##   mean=48.93278, MSE=4646.262 
##   left son=4 (4087 obs) right son=5 (271 obs)
##   Primary splits:
##       wine        splits as  --LLR--LLL--LLLLLLLLLLLL-LL--RLLL-RLL--LLLL--LLLLL-LLLLL-RLLLLLLL-RL-LLL-LLL--LRLLL--L--RL-L--LLLL---LL-LL--LLLLRR-LLLL-RLLLLRLLLL-L-RL-LLLR-L--LLLL-L-LLLLL-LLLLRLLRLLRL-LLLLLLRLLLLLRLLL---LLLL-L-LL-LL-LL-LLLR---LLLRLLLL-LR--L--LLLRLRRLLLL--LLL-RLL--LRRLLL--LLLLL----LL-LLL-LLL-L-L-LLLLLLLLL-LLL-LLLLLLL--LLLL--L-L-L-L-RLL-LLLL-LL---L--LLR-R-LRLLRLLL-LLLRL-L-R-RLL-LL-L-L---RLL--L-LLLL-L---LRLLLLLLL--RLL-LLL-L-LLLLLL-----L----L--LLLL-L--LRLLR-LRL--L--RLLL-LLLLLRRLL--LRL--RLLLL--RLLL--LL-LLRLLLLLL--LR-LL-LL-LLL--R--RL-L-L--L--LL--L--LL-RL-LLLLL-LLL-LLLLLLLL-L-L-LRL-LLL-RR-LLRL--L-L--LL-L-LLLL-L-RLLLL-LL-L--RLL-LLL--LLLLLLLLRLLL-LL-LLLLL-LLL--LRL-LLLLLLL-L-LLLLRLLRLLLR---LLL---LRLL---L-L---LLLLLLLLLLL----LLLL---L-LLLLLLRRRLR-L---L-LL-LLLLL-LLL--LLL-LLLL-RLLRLL--LLL--L-LLL---R-R-LR--LL-LRL---LL-L-L-L----LLLLLLLLL-LRLL-RRRLLLL-L-LLL-LL-LLLLLL, improve=0.4082101, (0 missing)
##       winery      splits as  -LLLLLLLRLLL-LR-LLLLLLRLLL-LLRLLLLLLLL---L-LLL--L--LLLL---LL-LLLL-L--LLLL-L-LLLLR-LLLR-LL-LLLL-LLLLLLLLLLLRL---LL-LLLLLL-----L-L-LL-LRL-LLLLLL-LLL-LLRLLLLLLLLLLLLLL-LL-LLLR---LLLL-L--LRL-LL-LLLRL-L-L-LL-LL-LLLRLL-L-LL-LLLR--L-LL-L-LRLLL--L-LLLLLLLLL-L-LL-LLRLL-LLLLL-LLLLLL-L--L-LL-LLLLLL-LL--LLLLR-LLLL--LLR--RLRRLLLLL-LLLLLLLL-LLL-L-LLLL-R--LLLLRRLLLL-LLLL-LLLL-LLL---RLL-L-LLLLLLL-L--LLLLLLLLLLLL--L--RL-LLLLL----LL-RLRRRLLLL-RL-LLL-L-LLLR-LLLLLR--LLLLLL-RLLLLL-LLL-L-LLLLL-L-L, improve=0.2804499, (0 missing)
##       rating      &lt; 4.45   to the left,  improve=0.2244645, (0 missing)
##       num_reviews &lt; 386    to the right, improve=0.1585326, (0 missing)
##       year        &lt; 2010.5 to the right, improve=0.1194112, (0 missing)
##   Surrogate splits:
##       winery splits as  -LLLLLRLRLLL-LL-LLLLLLRLLL-LLRLLLLLLLL---L-LLL--L--LLLL---LL-LLLL-L--LLLL-L-LLLLR-LRLR-LL-LLLL-LLLRLLLLLLLRL---LL-LLLLLL-----L-L-LL-LRL-LLLLLL-LLL-LRRLLRLLLLLLLLLLL-LL-LLLL---LLLL-L--LRL-LL-LLLLL-R-L-LL-RL-LLLLLL-L-LL-LLLR--L-LL-L-LLLLL--L-LLLLLLLLL-L-LL-LLLLL-LLLLL-LLLLLL-L--L-LL-LRLLLL-LL--LLLLR-LLLL--LLR--RLRRLLLLL-LLLLRLLL-LLL-L-LLLL-R--LLLLLRLLLL-LLLL-LLLL-LLL---RLL-L-LLLLLLR-L--LRLLLLLRLLLL--L--RL-LLLLL----LL-RLLRRLLLL-RL-LLL-R-LLLR-LLLLLR--LLLLLL-LLLLLL-LLL-L-RLLLL-L-L, agree=0.966, adj=0.450, (0 split)
##       rating &lt; 4.55   to the left,  agree=0.945, adj=0.111, (0 split)
##       year   &lt; 1990   to the right, agree=0.944, adj=0.103, (0 split)
##       region splits as  -LLLLLLLL-LLLLLLRLLR-LLRLLL--LL-LLLLL-L-RLRLRLLLL-LLLLL--L-LLLLLLLLLLLL--LLL, agree=0.941, adj=0.059, (0 split)
## 
## Node number 3: 73 observations,    complexity param=0.08338496
##   mean=954.2058, MSE=389169.5 
##   left son=6 (50 obs) right son=7 (23 obs)
##   Primary splits:
##       wine        splits as  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------L-----------------------------------------------------------------------------------------------------------------------------------------L--------------------------------------------------------R---------------R---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R--------------------------------------------------------------L------------------------------------------------------------------------------------------------------L-----------------------------LL-------------------------------------------------------------------, improve=0.3155169, (0 missing)
##       winery      splits as  ------------------------R----------------------------------L---L---------------------------------------L-------------------------------------------------------------------R-----------R-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------L------------------L-------------------------------, improve=0.3155169, (0 missing)
##       region      splits as  --------R-----------------------------------L--------R---L-L---------L------, improve=0.2168240, (0 missing)
##       type        splits as  --------LRRLL------L-, improve=0.2168240, (0 missing)
##       num_reviews &lt; 109.5  to the right, improve=0.1796302, (0 missing)
##   Surrogate splits:
##       region      splits as  --------R-----------------------------------L--------R---L-L---------L------, agree=0.877, adj=0.609, (0 split)
##       type        splits as  --------LRRLL------L-, agree=0.877, adj=0.609, (0 split)
##       body        &lt; 4.5    to the right, agree=0.836, adj=0.478, (0 split)
##       num_reviews &lt; 67.5   to the right, agree=0.795, adj=0.348, (0 split)
##       year        &lt; 2014.5 to the left,  agree=0.712, adj=0.087, (0 split)
## 
## Node number 4: 4087 observations,    complexity param=0.01482093
##   mean=37.71838, MSE=630.4267 
##   left son=8 (2687 obs) right son=9 (1400 obs)
##   Primary splits:
##       wine        splits as  --LL---RRL--LLRRLLRLRLRL-LL---RRL--LL--LLLR--LLLRL-RLLLL--RLRRRRR--L-LLL-RRR--L-LLL--L---R-R--LLLL---RL-LL--LRRL---LLLL--LRLL-RRRL-L--L-RLR--L--RRLL-L-LRLLR-LLLL-RL-RR-L-RRLRRR-RRLLL-LLR---LLRR-L-LL-LL-LL-RRR----LLR-LRLL-L---L--LLL-L--RRLL--RLL--RL--R--RLR--RRLLR----LL-RLL-LRL-L-L-LRRRLRRLL-LLR-LLRRLLL--LLLL--R-R-L-L--LR-LLLR-LR---R--LR----R-LL-RLR-LLR-R-R----LL-LR-R-R----LR--R-LLLL-L---L-LRLRRLL---LR-LLL-L-RLRLLR-----R----R--LRRL-L--L-LL--R-R--L---RLL-LLLLL--LL--R-R---LLLR---RLR--LR-LR-RRLRLR--L--LR-LL-LLR------L-L-L--L--LL--L--RL--R-LLLLL-LRR-LRRRRLRL-R-L-L-L-LRR----RR-R--R-L--LR-R-RRRL-L--LLRL-LL-L---RL-RRL--LLRLRLRL-LLL-LL-LLRLL-RLL--R-L-LRLLRLL-L-RRLR-RL-RRR----LRL---R-RL---R-L---RRLLLRLRLRR----LLLR---L-LRLLLR---L--R---L-LL-LRLRL-RLL--RLR-LRLL--RR-RL--RLR--R-LLR-------R---RR-L-L---LL-R-L-L----RLLLLRLLL-R-RL----LLRR-L-LLL-RL-LLRRLR, improve=0.6183481, (0 missing)
##       winery      splits as  -RLRRR-L-RLL-RR-RLLRLR-LRR-RL-LLRRRLRL---R-LLR--L--LRLR---LR-RRRL-L--LLRL-L-LLRLR-LLR--RL-RRLR-LLRRLRRRLLL-R---LL-RLRRRL-----R-L-RR-L-L-RLLLRL-RRL-R-RRLRLRLLRLRRRRR-LL-RLRR---LLRL-R--RRR-LL-LLLRR-L-L-LR--L-LRRRLL-R-RL-LLR---L-LL-L-RRLRL--L-LRRLRLRLR-R-LL-RRRLL-LLLLL-RLLLLL-L--L-LR-R-LLLL-RL--LRLR--RRLR--LR---LL--LRRRL-RLRL-LRR-LRR-L-LLLL----RLLLLRRRLL-RLLL-LLLL-LLL----LR-R-LRRRRLL-L--R-RRRRL-LLLR--R---R-LRLLR----RR--LR-LRRLL-RL-LRL---LLR--LRRLL---LRLRRR-RLRRLR-LLL-R--LLLL-R-L, improve=0.4686453, (0 missing)
##       year        &lt; 2014.5 to the right, improve=0.2151698, (0 missing)
##       num_reviews &lt; 389.5  to the right, improve=0.1672325, (0 missing)
##       region      splits as  -LLLLLRRL-RLRRLR-RLR-LL-LRL--LR-RRRRL-R-RR-LRRLRL-RLLRL--R-RRLLRLRLRRRL--LRL, improve=0.1543332, (0 missing)
##   Surrogate splits:
##       winery      splits as  -RLRLL-L-RLL-RR-RLLLLR-LRR-RL-LLRRLLRL---R-LLL--L--LRLL---LR-LRLL-L--LLRL-L-LLRLR-LLR--RL-LRLR-LLLRLRRRLLL-R---LL-RLRRLL-----L-L-RR-L-L-RLLLLL-RRL-R-LRLRLRLLRLRRRRR-LL-LLRR---LLRL-R--RLR-LL-LLLRR-L-L-LR--L-LRLRLL-R-RL-LLR---L-LL-R-LRLRL--L-LLRLRLRLL-R-LL-LRRLL-LLLLL-RLLLLL-L--L-LL-L-LLLL-LL--LLLR--RRLL--LR---LL--LRLRL-RLRL-LRR-LLR-L-LLLL----RLLLLRLRLL-RRLL-LLLL-LLL----LR-R-LRRRRLL-L--L-LRLLL-LLLR--R---R-LRLLR----LR--LR-LLRLL-LL-LLL---LLL--RRRLL---LRLRRL-RLRRLL-LLL-L--LLLL-L-L, agree=0.930, adj=0.794, (0 split)
##       year        &lt; 2011.5 to the right, agree=0.780, adj=0.359, (0 split)
##       region      splits as  -LLLLLRLL-LLLRLL-RLR-LL-LLL--LL-RRLLL-R-LL-LRLLRL-LLLRL--L-LRLLRLLLLLLL--LRL, agree=0.710, adj=0.153, (0 split)
##       type        splits as  LRRLLLLLLRLLLLLLLLRLL, agree=0.707, adj=0.145, (0 split)
##       num_reviews &lt; 386    to the right, agree=0.698, adj=0.119, (0 split)
## 
## Node number 5: 271 observations,    complexity param=0.03461715
##   mean=218.0592, MSE=34709.41 
##   left son=10 (257 obs) right son=11 (14 obs)
##   Primary splits:
##       winery splits as  -L----L-L-----L-------L-L----L---LL------------------------L----------L---------L--L-L----L------LL-----L-L--------------------------L--------------LR--L------------------L------L-----L--------L--L-L----L---L-------L-----L----------L-L----------------------L-----------L-------------L-------------L-L------LL--L-LL---L------L------L--------L------LL-----L-L-------------L--------L--L-----L--L--L---------L--L--L--------L-LLRL----L------L---LL------L------L--L------------L--------, improve=0.39561390, (0 missing)
##       type   splits as  --LLLL-LLLLLLL-LL-LR-, improve=0.16341780, (0 missing)
##       region splits as  ---L-L--L-------LL-L-L-L-L---L---L-L----L-L-LL----L--L---L-LLL---L---R---LL-, improve=0.16341780, (0 missing)
##       rating &lt; 4.75   to the left,  improve=0.13420570, (0 missing)
##       year   &lt; 2013.5 to the right, improve=0.09244459, (0 missing)
##   Surrogate splits:
##       wine   splits as  ----L------------------------L----R----------------------L--------L------------L--------L-----------------------LL------L----L-------L-----L---------------------L--L--L--------L-----L-------------------------L------R------L--------L-LL----------L-----LL------------------------------------------------------------------L------------------L-L--L--L-------L----L-L------------L----------------L---------L-------------------------------------L--L--L------L---------LL-----L---L------L----------L---------L------------L--L--------------------L--------------------------L------LL---L--------------------L-----------L----------------L-------------------L----------------L--L---L----------L-----------------------------------------LLL-L------------------------------L--L-----------------L-L--L------L---------------------------L---LLL--------------------, agree=0.959, adj=0.214, (0 split)
##       region splits as  ---L-L--L-------LL-L-L-L-L---L---L-L----L-L-LL----L--L---L-LLL---L---R---LL-, agree=0.956, adj=0.143, (0 split)
##       type   splits as  --LLLL-LLLLLLL-LL-LR-, agree=0.956, adj=0.143, (0 split)
## 
## Node number 6: 50 observations,    complexity param=0.03452879
##   mean=716.5438, MSE=226049.2 
##   left son=12 (23 obs) right son=13 (27 obs)
##   Primary splits:
##       year        &lt; 2004.5 to the right, improve=0.32840130, (0 missing)
##       num_reviews &lt; 309.5  to the right, improve=0.16080040, (0 missing)
##       rating      &lt; 4.65   to the left,  improve=0.08287315, (0 missing)
##       winery      splits as  -----------------------------------------------------------L---L---------------------------------------R-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R------------------R-------------------------------, improve=0.04522092, (0 missing)
##       wine        splits as  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------L-----------------------------------------------------------------------------------------------------------------------------------------R-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R------------------------------------------------------------------------------------------------------L-----------------------------RR-------------------------------------------------------------------, improve=0.04522092, (0 missing)
##   Surrogate splits:
##       wine        splits as  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------L-----------------------------------------------------------------------------------------------------------------------------------------R-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R------------------------------------------------------------------------------------------------------L-----------------------------RL-------------------------------------------------------------------, agree=0.76, adj=0.478, (0 split)
##       winery      splits as  -----------------------------------------------------------L---L---------------------------------------R-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R------------------R-------------------------------, agree=0.68, adj=0.304, (0 split)
##       region      splits as  --------------------------------------------R------------R-L---------L------, agree=0.68, adj=0.304, (0 split)
##       type        splits as  --------R--RL------L-, agree=0.68, adj=0.304, (0 split)
##       num_reviews &lt; 124    to the right, agree=0.64, adj=0.217, (0 split)
## 
## Node number 7: 23 observations,    complexity param=0.01208131
##   mean=1470.862, MSE=354055.4 
##   left son=14 (9 obs) right son=15 (14 obs)
##   Primary splits:
##       year        &lt; 2011.5 to the right, improve=0.15948200, (0 missing)
##       rating      &lt; 4.65   to the right, improve=0.13463400, (0 missing)
##       num_reviews &lt; 62.5   to the right, improve=0.12780900, (0 missing)
##       body        &lt; 4.5    to the right, improve=0.02788812, (0 missing)
##       winery      splits as  ------------------------R--------------------------------------------------------------------------------------------------------------------------------------------------R-----------L--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------, improve=0.02788812, (0 missing)
##   Surrogate splits:
##       rating      &lt; 4.75   to the right, agree=0.696, adj=0.222, (0 split)
##       num_reviews &lt; 41     to the left,  agree=0.696, adj=0.222, (0 split)
##       winery      splits as  ------------------------R--------------------------------------------------------------------------------------------------------------------------------------------------L-----------R--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------, agree=0.652, adj=0.111, (0 split)
##       wine        splits as  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R---------------L---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------R------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------, agree=0.652, adj=0.111, (0 split)
##       region      splits as  --------L--------------------------------------------R---R------------------, agree=0.652, adj=0.111, (0 split)
## 
## Node number 8: 2687 observations
##   mean=23.46677, MSE=77.10961 
## 
## Node number 9: 1400 observations
##   mean=65.0713, MSE=554.3952 
## 
## Node number 10: 257 observations,    complexity param=0.01148682
##   mean=190.7092, MSE=11604.8 
##   left son=20 (149 obs) right son=21 (108 obs)
##   Primary splits:
##       wine   splits as  ----R------------------------L---------------------------L--------R------------L--------L-----------------------LR------L----L-------R-----L---------------------R--L--R--------L-----L-------------------------L-------------L--------L-LR----------L-----LL------------------------------------------------------------------R------------------L-R--R--R-------R----R-R------------L----------------R---------L-------------------------------------R--R--L------R---------LL-----L---L------L----------L---------R------------L--R--------------------R--------------------------L------RL---R--------------------L-----------R----------------R-------------------R----------------L--L---R----------L-----------------------------------------LLL-R------------------------------L--R-----------------L-R--R------R---------------------------R---LRL--------------------, improve=0.41402420, (0 missing)
##       winery splits as  -L----L-R-----R-------L-R----R---RL------------------------R----------L---------R--L-R----L------RL-----L-R--------------------------L--------------L---L------------------R------R-----R--------R--R-R----L---R-------L-----L----------R-L----------------------R-----------R-------------L-------------L-R------LR--R-RR---R------L------R--------R------RR-----L-L-------------L--------L--R-----L--R--L---------R--L--L--------R-RR-L----R------L---LR------R------R--R------------L--------, improve=0.34110450, (0 missing)
##       year   &lt; 2016.5 to the right, improve=0.11247530, (0 missing)
##       region splits as  ---L-L--R-------LL-L-L-L-R---L---R-L----R-L-LL----L--L---L-LLR---L---L---LR-, improve=0.09828861, (0 missing)
##       rating &lt; 4.55   to the left,  improve=0.08983699, (0 missing)
##   Surrogate splits:
##       winery splits as  -L----L-R-----L-------L-R----R---RL------------------------L----------L---------L--L-L----L------LL-----L-R--------------------------L--------------L---L------------------R------R-----R--------R--L-L----L---R-------L-----L----------R-L----------------------L-----------R-------------L-------------L-R------LR--L-LL---R------L------L--------R------RL-----L-L-------------L--------L--L-----L--L--L---------R--L--L--------R-RR-L----L------L---LL------R------L--R------------L--------, agree=0.899, adj=0.759, (0 split)
##       region splits as  ---L-L--R-------LL-R-L-L-R---L---R-L----R-L-LL----L--L---R-LLR---L---L---LR-, agree=0.658, adj=0.185, (0 split)
##       rating &lt; 4.55   to the left,  agree=0.650, adj=0.167, (0 split)
##       year   &lt; 2005.5 to the right, agree=0.638, adj=0.139, (0 split)
##       type   splits as  --LRLR-LLLLRLR-LL-RL-, agree=0.626, adj=0.111, (0 split)
## 
## Node number 11: 14 observations
##   mean=720.1264, MSE=193040.9 
## 
## Node number 12: 23 observations
##   mean=421.34, MSE=56728.43 
## 
## Node number 13: 27 observations
##   mean=968.0137, MSE=232813.5 
## 
## Node number 14: 9 observations
##   mean=1174.492, MSE=45966.15 
## 
## Node number 15: 14 observations
##   mean=1661.386, MSE=459348.1 
## 
## Node number 20: 149 observations
##   mean=131.6958, MSE=5364.493 
## 
## Node number 21: 108 observations
##   mean=272.1258, MSE=8780.789</code></pre>
<p>In our analysis, the decision tree model started with 4431 observations and successfully split them into child nodes based on certain criteria, resulting in a deviance of 107497100.0 and a predicted value of 63.84701 for the root node. The complexity of interpreting the tree is compounded by the large number of levels in some of the attribute variables, which makes it challenging to understand the model’s decision-making process using this tree.</p>
<p>One particular challenge arises from the inclusion of a large number of wine names as features in the decision tree model. The sheer volume of features and their unique names can make interpretation difficult. However, by using feature importance, we can gain insight into which wine attributes, i.e. features are most influential in predicting the target variable. Features with higher importance values are more critical in the model’s decision-making process.</p>
<p>Understanding feature importance is crucial in data science as it not only helps prioritise efforts but also enhances the transparency of the model. By identifying the most impactful factors, we can improve the interpretability of the model’s results and make our data science reports more informative and actionable.</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="demonstration.html#cb517-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Get feature importance</span></span>
<span id="cb517-2"><a href="demonstration.html#cb517-2" tabindex="-1"></a><span class="er">&gt;</span> importance <span class="ot">&lt;-</span> <span class="fu">varImp</span>(tree_model)</span>
<span id="cb517-3"><a href="demonstration.html#cb517-3" tabindex="-1"></a><span class="sc">&gt;</span> </span>
<span id="cb517-4"><a href="demonstration.html#cb517-4" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Print the feature importance</span></span>
<span id="cb517-5"><a href="demonstration.html#cb517-5" tabindex="-1"></a><span class="er">&gt;</span> <span class="fu">print</span>(importance)</span></code></pre></div>
<pre><code>##                Overall
## body        0.02788812
## num_reviews 0.90531862
## rating      0.97093847
## region      0.63286356
## type        0.38024180
## wine        2.34867729
## winery      2.26305636
## year        1.15760534
## acidity     0.00000000</code></pre>
<p>The feature importance scores provide insight into the relative importance of each feature in the model for predicting the target variable. Features with higher importance scores have more influence on accurate predictions. In this case, the wine feature has the highest importance score of 2.3487, indicating its significant impact on predictions. The winery feature follows closely behind with a score of 2.2631, followed by rating with a score of 0.9709, and year with a score of 1.1576. Conversely, features with lower importance scores, such as body and acidity, have less influence on predictions.</p>
<p>We realise that interpreting a decision tree with a large number of features like wine names requires careful analysis and consideration of the unique characteristics of the dataset. Features such as wine names can lead to a high-dimensional feature space, making it challenging to visualise and comprehend the decision-making process of the model. It is important to understand the underlying relationships between features and the target variable to ensure the model’s predictions are reliable and actionable.</p>
</div>
<div id="report-conclusion" class="section level2 unnumbered hasAnchor">
<h2>Report Conclusion<a href="demonstration.html#report-conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The proposed <code>tree_model</code> offers valuable insights into the dataset, highlighting key features like <code>wine</code>, <code>winery</code>, <code>rating</code>, and <code>year</code> that significantly influence predictions. However, the model’s complexity, particularly with a large number of levels in some attribute variables, poses challenges for interpretation. Future models could benefit from simplification techniques or alternative algorithms to improve interpretability. Additionally, while the feature importance analysis provides useful information, it would be beneficial to explore the interaction effects between features, which could further enhance the model’s predictive power. Furthermore, the high-dimensional feature space created by including a large number of wine names as features underscores the importance of feature selection techniques to identify the most relevant features for the model. Overall, future modelling efforts could focus on improving interpretability, exploring feature interactions, and refining feature selection processes to build more robust and insightful models.</p>
</div>
<div id="key-insights" class="section level2 unnumbered hasAnchor">
<h2>Key Insights<a href="demonstration.html#key-insights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the case study of enhancing data science projects with ChatGPT using the <code>wine_data</code> dataset in R, several positives and negatives emerged. On the positive side, ChatGPT proved to be a useful tool in facilitating data exploration and preprocessing, contributing to the cleaning and preparation of datasets. Additionally, ChatGPT’s ability to summarise findings, create visualisations, and generate reports enhanced the communication of results and insights. However, there are some considerations to note. ChatGPT’s effectiveness may be limited by the quality and quantity of the data it is trained on, potentially leading to biased or inaccurate recommendations. Furthermore, while ChatGPT can assist in selecting machine learning algorithms, it may not always suggest the most optimal approach for every dataset. Therefore, it is essential to use ChatGPT as a supportive tool rather than relying solely on its suggestions, ensuring a balanced approach to data science project development.</p>
<p>Despite these considerations, integrating ChatGPT into the data science workflow can bring valuable insights, streamline processes, and ultimately enhance the overall success of the project.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="overview-7.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="your-turn.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
